### ISSUE TITLE
Update documentation on Data Commons Architecture

### ISSUE THREAD

**Issue by caldeirav** [os-climate/os_c_data_commons#110]
Update architecture documentation in the repo to match scope of technical deep dive and also include the discussions about data management / security so this can serve as a reference with data stakeholders once we go public.

**Comment by MichaelTiemannOSC** [comment]
With several datasets presently represented in the Data Commons, it would be great to identify the key issues those datasets raise in terms of licensing, sourcing, update frequency, metadata, etc., and then use those themes to spell out the best practices intended by the architecture and the implementation.  I won't be offended if one of the pipelines I created is revealed to fall short of the goals in one or more categories!
