### ISSUE TITLE
Set up Cert-Manager or cert expiration for OSC Cluster

### ISSUE THREAD

**Issue by HumairAK** [os-climate/os_c_data_commons#114]
Ideally we would want cert-manager to auto issue new certs as they expire so as to not have to deal with this manually. But if this is not possible then we should at the least have alerts around certs that are close to expiration, otherwise we will incur unexpected downtime/service disruptions for all services on this cluster.

**Comment by redmikhail** [comment]
While we have cert-manager installed on both clusters , dns01 challenge wasn't working due to split-horizon dns resolution for Openshift on AWS . There is some of things that we can still try short of using custom deployment vs cert-manager operator . Details are mentioned in the issue 1974 in operate-first github repo . Details of things to try are here https://github.com/operate-first/apps/issues/1974#issuecomment-1362202186

**Comment by HeatherAck** [comment]
Mikhail testing and creating PR

**Comment by redmikhail** [comment]
The solution  could be either deployment of the cert manager operator bypassing OLM mechanism (eg. deployment of the controller explicitly with adding required arguments https://cert-manager.io/docs/configuration/acme/dns01/#setting-nameservers-for-dns01-self-check )  or using OLM but adjusting clusterserviceversion object something like `oc patch csv $CERT_MANAGER_CSV_NAME --type='json' -p '[{"op": "add", "path": "/spec/install/spec/deployments/0/spec/template/spec/containers/0/args/-", "value":'--dns01-recursive-nameservers-only'}, {"op": "add", "path": "/spec/install/spec/deployments/0/spec/template/spec/containers/0/args/-", "value":'--dns01-recursive-nameservers=1.1.1.1:53'}]'`   Both of these approaches are not ideal from perspective of ArgoCD provisioning

**Comment by redmikhail** [comment]
Considering complexity of updating dependent CSV object with ArgoCD , went with RH Cert Manager Operator (https://docs.openshift.com/container-platform/4.10/security/cert_manager_operator/cert-manager-operator-install.html) . Operator provide additional options of configuring cert-manager controller resolving issue mentioned above. It appears that operator will become standard in future releases of Openshift

**Comment by redmikhail** [comment]
odh-cl1 environment is fully updated (see PR's 10 and 11)

**Comment by redmikhail** [comment]
odh-cl2 cluster updated to use cert-manager as well . Instructions for adding and updating certs will be tracked separetly

**Comment by redmikhail** [comment]
@MightyNerdEric @ryanaslett FYI
