### ISSUE TITLE
Not able to push on git - Write access to repository not granted.

### ISSUE THREAD

**Issue by andraNew** [os-climate/os_c_data_commons#122]
I am not able to push on git, although I am able to do other operations such as clone. I use my User access token.
![image](https://user-images.githubusercontent.com/62877651/151170807-12a6b985-18c8-4097-8ef6-4f1c20c70537.png)

**Comment by MichaelClifford** [comment]
I think you do not have write permissions to the upstream repository `os-climate/corporate_data_pipeline`. You should push changes to your own fork of the repo and then open a pull request from your fork to the upstream and have your code reviewed and merged by another contributor. 

Here is a [diagram](https://github.com/kubernetes/community/blob/master/contributors/guide/git_workflow.png) from the kubernetes community that provides a clear depiction of the git workflow.

**Comment by MichaelTiemannOSC** [comment]
Andra, if this is working for you please close the issue.

**Comment by andraNew** [comment]
Issue is closed, thanks for the help

**Comment by Ganapathi525** [comment]
i try this but won't work

**Comment by MichaelTiemannOSC** [comment]
@Ganapathi525 great to see you here at OS-Climate!  The practice we are following from Red Hat is that users should fork, not clone repositories, and present their PRs from the fork against the appropriate branch within the main repository (main, develop, whatever).  If you create a PR, it can be reviewed and merged by maintainers.  Over time, you might be nominated to join the ranks of maintainers.
