### ISSUE TITLE
Review of Data Vault requirements based on LSEG Data Provisioning for OS-Climate

### ISSUE THREAD

**Issue by caldeirav** [os-climate/os_c_data_commons#124]
LSEG has shared a view of vault requirements based on the ITR scenario (DataVault-OS-Climate-forMichael.pptx). We will use this issue for analysis and requirement review and spin new issues for Data Commons accordingly.

**Comment by MichaelTiemannOSC** [comment]
Just noting that an email was sent today.

**Comment by caldeirav** [comment]
As the review was done and we have agreed to go into a deep-dive with LSEG, closing this and focusing on follow up in particular #130 that should get discussions started in the deep-dive itself.
