### ISSUE TITLE
Add a rule for non-activity to manage JupyterHub sessions

### ISSUE THREAD

**Issue by caldeirav** [os-climate/os_c_data_commons#127]
In order to claim back memory used by idle JupyterHub sessions, implement a rule for idle sessions. For a start, we should automatically kill sessions that have been idle for 3 days or more.

**Comment by HeatherAck** [comment]
based on @MichaelTiemannOSC experience, timeout seems to be every 24 hours.  @redmikhail to see if "kill" setting can be modified to be 3 days and provide a warning 10 minutes prior to kill.

**Comment by HeatherAck** [comment]
@redmikhail to work with @HumairAK to see if settings can be changed; @MichaelTiemannOSC to provide error/screen shot

**Comment by HumairAK** [comment]
This is for adding a jupyterhub idle culler, to reclaim unused/idle pods.

**Comment by HeatherAck** [comment]
@redmikhail will follow up with @HumairAK
