### ISSUE TITLE
Change default logout time in Superset from 5min to 1hour

### ISSUE THREAD

**Issue by caldeirav** [os-climate/os_c_data_commons#128]
In SuperSet, we get logged out of the session too quickly. Could we have auto-logout timing changed to 1 hour?Likely this should be done via setting PERMANENT_SESSION_LIFETIME in config file as per: https://superset.apache.org/docs/installation/configuring-superset/

**Comment by HeatherAck** [comment]
@caldeirav are you still having issues?  Closing - reopen if needed
