### ISSUE TITLE
Deploy OSC Data Commons Stable Cluster

### ISSUE THREAD

**Issue by erikerlandson** [os-climate/os_c_data_commons#136]
This issue is a replacement for the "production" component of #118. With the completion of the new Development cluster, it is useful to close that issue out, and track the discussion and progress of the eventual PROD cluster on this new issue.

**Comment by HeatherAck** [comment]
pending understanding/documentation on stable versions of all tools - need actual versions of tools to deploy

**Comment by HeatherAck** [comment]
closing as dup
