### ISSUE TITLE
Trino error message "failed to get status"

### ISSUE THREAD

**Issue by MichaelTiemannOSC** [os-climate/os_c_data_commons#154]
I'm working on a bulk import script for SEC DERA data.  A previous run was almost successful (my batch_size estimate was a bit too high), but after deleting those tables and trying again I got this message pretty quickly:

TrinoQueryError: TrinoQueryError(type=INTERNAL_ERROR, name=GENERIC_INTERNAL_ERROR, message="Failed to get status for file: s3a://osc-datacommons-s3-bucket-dev02/data/sandbox.db/dera_num/metadata/snap-4704618140689018801-1-dabd4b8d-6822-4d03-b111-52f87b7c925c.avro", query_id=20220401_112929_00240_bm8rx)

@erikerlandson

**Comment by MichaelTiemannOSC** [comment]
We suspect this might be fixed with Trino 372 or later (currently fails on 362 and 371).  Another tidbit: steps to get here included making queries that failed due to too-large batch size.  Once the batch size was fixed the failure changed from a batch-size failure to this failure.  No idea whether a too-large batch size is a necessary pre-condition to confusing Trino about the metadata files.

**Comment by MichaelTiemannOSC** [comment]
It looks to me like snapshot_ids are being allocated and managed in two different places.

When I drop dera_num and then create it, a json file references a snapshot_id from just before 7AM:

```
  "current-snapshot-id" : 7228312865295554902,
  "snapshots" : [ {
    "snapshot-id" : 7228312865295554902,
    "timestamp-ms" : 1648810696509,
    "summary" : {
      "operation" : "append",
      "changed-partition-count" : "0",
      "total-records" : "0",
      "total-data-files" : "0",
      "total-delete-files" : "0",
      "total-position-deletes" : "0",
      "total-equality-deletes" : "0"
    },
    "manifest-list" : "s3a://osc-datacommons-s3-bucket-dev02/data/sandbox.db/dera_num/metadata/snap-7228312865295554902-1-1f5744cf-d628-4863-b231-fffba0392c3c.avro"
  } ],
  "snapshot-log" : [ {
    "timestamp-ms" : 1648810696509,
    "snapshot-id" : 7228312865295554902
  } ],
```

But the table itself references a different snapshot_id:

```
trino:sandbox> select snapshot_id from "dera_num$snapshots";
     snapshot_id     
---------------------
 2690580821138189265 
(1 row)

Query 20220401_173215_00121_4rzyy, FINISHED, 2 nodes
Splits: 3 total, 3 done (100.00%)
0.27 [1 rows, 451B] [3 rows/s, 1.63KB/s]
```

The `2690580821138189265` number shows up in the Trino error message of my latest run:

```
trino:sandbox> delete from dera_num;

Query 20220401_171935_00119_4rzyy, FAILED, 1 node
Splits: 1 total, 0 done (0.00%)
0.18 [0 rows, 0B] [0 rows/s, 0B/s]

Query 20220401_171935_00119_4rzyy failed: Failed to get status for file: s3a://osc-datacommons-s3-bucket-dev02/data/sandbox.db/dera_num/metadata/snap-2690580821138189265-1-5e4b75af-3704-4cf3-9d71-afc353bad536.avro
```

What is surprising is that this bad behavior does not afflict the dera_sub table, which I've been able to delete and recreate no problem.

**Comment by MichaelTiemannOSC** [comment]
https://github.com/apache/iceberg/issues/4472

**Comment by MichaelTiemannOSC** [comment]
Could this be related: https://github.com/trinodb/trino-python-client/issues/95?  osc-ingest-tools does use fetchall (the workaround), but the fact that there are potential pathways in python to miss errors is concerning...

**Comment by MichaelTiemannOSC** [comment]
And now the Hive metastore seems to be down:

```
TrinoExternalError: TrinoExternalError(type=EXTERNAL, name=HIVE_METASTORE_ERROR, message="Failed connecting to Hive metastore: [hive-metastore-osc-datacommons-dev:9083]", query_id=20220404_113433_00153_4rzyy)
```

**Comment by HumairAK** [comment]
@MichaelTiemannOSC guessing this is on osc-cl2 cluster. Will take a look after morning meetings.

**Comment by HumairAK** [comment]
> And now the Hive metastore seems to be down: 

@MichaelTiemannOSC is this still the case? I see queries being ran/completing successfully.

**Comment by MichaelTiemannOSC** [comment]
I received this info explaining how to clean up the mess from the trino/iceberg slack channel: https://trinodb.slack.com/archives/CJ6UC075E/p1649094031432789

**Comment by erikerlandson** [comment]
JDBC catalog support could be huge
https://github.com/trinodb/trino/pull/11772

**Comment by erikerlandson** [comment]
I'm interested in their prescription for removing files, because I'm pretty sure that wasn't working for me when I tried it.  Unless I was missing something

**Comment by MichaelTiemannOSC** [comment]
I am tempted to follow the prescription of removing files because (1) it cleans up messy storage and (2) it may well force the issue of re-initializing the whole underlying storage for this instance if something goes really wrong.  But I'd prefer to just see the storage re-initialized so that there are not dangling metadata references and so that there are no extraneous files left lying around after dropping tables and telling trino it's OK to delete them.

**Comment by MichaelTiemannOSC** [comment]
Problem seems to have gone away and not come back after refreshing CL2.
