### ISSUE TITLE
Need more meaningful interfaces to Iceberg

### ISSUE THREAD

**Issue by MichaelTiemannOSC** [os-climate/os_c_data_commons#157]
Iceberg's SQL-ish language (which include things like `ALTER TABLE ... DROP PARTITION FIELD`) cannot be used directly in Trino.  The three obvious options are:

1.  Add some kind of Spark instance that people can use when they need to fix things that cannot be fixed via Trino or Python
2. Enhance Trino to understand more of Spark DDL
3. Create a python library where commands can be translated to Spark API calls

**Comment by caldeirav** [comment]
I would not think having a second compute engine for Iceberg operation is the solution here. How would we ensure consistency in data access between Spark and Trino for example?

Could we start maybe by documenting in this issue the Iceberg operations that are required but not supported by Trino?

**Comment by MichaelTiemannOSC** [comment]
Seems like the Trino connector has made a ton of progress in this space that makes this generic request less pressing.  Will open new cases when new specific limitations appear.
