### ISSUE TITLE
Jupyterhub server fails

### ISSUE THREAD

**Issue by andraNew** [os-climate/os_c_data_commons#162]
I currently experiencing once more issue 121 that was resolved last time by  increasing from 2GB to 16GB the memory

![image](https://user-images.githubusercontent.com/62877651/150765527-973269c0-e383-4cbd-903b-7a876db89f5b.png)

**Comment by andraNew** [comment]
@erikerlandson @MichaelTiemannOSC

**Comment by JeremyGohBNP** [comment]
I am experiencing the same issues. I cannot start a server. Is there maintenance going on?

**Comment by MichaelTiemannOSC** [comment]
I just tried creating a corp-data-pipeline notebook on CL1 and was succeesful.  I'll ask @HumairAK if he sees anything in the logs.

**Comment by JeremyGohBNP** [comment]
> I just tried creating a corp-data-pipeline notebook on CL1 and was succeesful. I'll ask @HumairAK if he sees anything in the logs.

We tried the AICoE-OS Climate Demo and it systematically fails

**Comment by MichaelTiemannOSC** [comment]
Ah.  @MichaelClifford @harshad16  can either of you say more about the status of the AICoE-OS Climate demo configuration?  I see there was a change two days ago to jupyterhub config files that mention AICoE.

**Comment by oindrillac** [comment]
cc: @chauhankaranraj @Shreyanand

**Comment by harshad16** [comment]
a transitive dependent package: markupsafe has removed a function `soft_unicode` in version 2.1.0 https://github.com/pallets/markupsafe/blob/b341ea3c59218e25a8ce2c1c2c5ca885e315e41e/CHANGES.rst#version-210

the jijna2 package which is a transitive package of flask and jupyterlab, uses the function in version below 2.11.0 , we would have downgrade the markupsafe package, to fix this issue.

**Comment by chauhankaranraj** [comment]
Hey folks, the `aicoe-osc-demo` image should now be fixed. I am able to spawn a JupyterHub pod on cl1 with that image, please let me know if the error is fixed for you or you're still running into this problem.

**Comment by erikerlandson** [comment]
Can we close this issue?

**Comment by MichaelTiemannOSC** [comment]
After this merge I went back to the JupyterLab hub server, and was immediately given the options I needed to start my notebook correctly.  Thanks!

**Comment by MichaelTiemannOSC** [comment]
I wrongly closed this issue, which is against `aicoe-osc-demo`, a notebook configuration that I don't use.  I thought it was fixing a different issue (https://github.com/operate-first/apps/issues/1918), which I also closed.  If this issue remains a problem, please reopen!
