### ISSUE TITLE
Create a DB connection for Trino in Superset on odh-cl2

### ISSUE THREAD

**Issue by caldeirav** [os-climate/os_c_data_commons#164]

**Comment by caldeirav** [comment]
In the new superset install accessible at https://superset-secure-odh-superset.apps.odh-cl2.apps.os-climate.org/ , I need to define a connection to Trino (trino-secure-odh-trino.apps.odh-cl2.apps.os-climate.org:443) preferably with admin and ability to Impersonate logged in user (caldeirav) for access rights reasons.

@HumairAK Could you point me to how this is done?

**Comment by HumairAK** [comment]
can I get a lgtm on: https://github.com/operate-first/apps/pull/1913 

I can't seem to locate these creds, so changing up the psw. Going to use this account to login to trino from superset.

**Comment by caldeirav** [comment]
This issue has been fixed with https://github.com/operate-first/apps/pull/1913
