### ISSUE TITLE
Trino ingestion fails with InvalidRequestError: A value is required for bind parameter

### ISSUE THREAD

**Issue by caldeirav** [os-climate/os_c_data_commons#165]

**Comment by caldeirav** [comment]
my insertion notebook fails after inserting a few hundred samples, with the exception: A value is required for bind parameter 'Unit' (Background on this error at: https://sqlalche.me/e/14/cd3x)"

Notebook: https://github.com/os-climate/data-platform-demo/blob/master/notebooks/gppd_ingest_2_load_data_trino.ipynb

**Comment by MichaelTiemannOSC** [comment]
There's a patch here that's not yet a PR (because waiting on executemany support in Trino to make obsolete): https://github.com/os-climate/osc-ingest-tools/edit/mdt-patch/osc_ingest_trino/trino_utils.py

Look at sqlform for text.

**Comment by erikerlandson** [comment]
closed by https://github.com/os-climate/osc-ingest-tools/issues/27
