### ISSUE TITLE
Superset certs show clock skew problem

### ISSUE THREAD

**Issue by MichaelTiemannOSC** [os-climate/os_c_data_commons#173]
I cannot access SuperSet on CL2 using the well-known link from the Developer Resources page that was working for me this morning: https://superset-secure-odh-superset.apps.odh-cl2.apps.os-climate.org/

<img width="926" alt="Screen Shot 2022-05-10 at 5 29 26 PM" src="https://user-images.githubusercontent.com/72577720/167725306-1487f562-e594-4b6d-8473-d816680c94f2.png">

Others were having different OAuth problems this morning that I didn't have (and which had worked for them before), but something definitely tenuous.

@redmikhail @erikerlandson

**Comment by redmikhail** [comment]
@MichaelTiemannOSC Unfortunately previous certificate has expired , it was renewed . Should be working now
