### ISSUE TITLE
Access Request for Data Commons platform

### ISSUE THREAD

**Issue by SKZHA** [os-climate/os_c_data_commons#176]
I would like to have access to Data Commons platform. 
FYI. I've been added to developper teams as well as odh-env-users.

My email : shikang.zhao@bnpparibas.com

**Comment by SKZHA** [comment]
Hey @erikerlandson, 
Newly onboarded on os-climate, I hope you can help me to get access to data commons platform. 
Please tell me if you need more information. Thanks!

**Comment by MichaelTiemannOSC** [comment]
@SKZHA I think you have been successfully using the credentials granted, so closing this issue.  If not, please re-open and we'll address.
