### ISSUE TITLE
update jupyterhub images to latest

### ISSUE THREAD

**Issue by erikerlandson** [os-climate/os_c_data_commons#178]
We have a few JH images that still have python 3.6, and they also don't have the latest `%horus` magic from thoth.

![image](https://user-images.githubusercontent.com/259898/171749653-917544d5-d10c-4537-9808-c5920f8e7f46.png)

**Comment by HumairAK** [comment]
can this be closed? @erikerlandson

**Comment by erikerlandson** [comment]
The lab-elyra image update is finished, and I can now run `%horus`.  I was going to keep this open for @harshad16 because he mentioned upgrading all the images, however if he wants to track that differently I am Ok to close this.

**Comment by HumairAK** [comment]
will keep it to the discretion of @harshad16 then, thanks @erikerlandson

**Comment by harshad16** [comment]
oh lets keep this open
i m updating the python 3.6 minimal image as well
it would have the jupyterlab-requirements and with that, we can close this.

**Comment by MichaelTiemannOSC** [comment]
Elsewhere I've suggested simply dropping Python 3.6: https://github.com/operate-first/apps/issues/2009

So many of the packages I track are removing support for it.  I think we are asking for trouble supporting anything earlier than Python 3.8.  It might even make sense to set a target for what version of Python we expect to support by the end of the year.

**Comment by erikerlandson** [comment]
FWIW, I agree we should avoid exposing any py3.6 images.  The python ecosystem makes this issue complicated, but more things break with py < 3.8 than work.

**Comment by MichaelTiemannOSC** [comment]
Can we drop the py3.6 images and close this out?

**Comment by MichaelTiemannOSC** [comment]
The latest spawn window on CL2 no longer advertises Py3.6.
