### ISSUE TITLE
DCO - As a user I want to be able to validate that all source code in an OSC  respository has been signed off with a DCO

### ISSUE THREAD

**Issue by eoriorda** [os-climate/os_c_data_commons#179]

**Comment by eoriorda** [comment]
Here's my sad story about the DCO:

https://github.com/os-climate/ITR/pull/109

Folks from LF have agreed to have a look at it.  I tried adding a signoff manually at the end of the commit message, but somehow that's not yet enough to make the robots happy.

M

The structure of world peace cannot be the work of one man, or one
party, or one nation...it must be a peace which rests on the cooperative
effort of the whole world. -- Franklin Delano Roosevelt

Part of the tragedy is of the artist is that there is no real goal in
achieving what you are naturally good at. The real satisfaction lies in
the things you accomplish by practice and effort.
  -- Joris van den Berg, commenting on the death of H. Cartier Bresson

Dream so big you can share -- me

**Comment by HeatherAck** [comment]
duplicate - @MightyNerdEric confirmed automatically signoff is not permitted/allowed via githooks
