### ISSUE TITLE
Cannot connect to Trino database via CloudBeaver service on OSC-CL2

### ISSUE THREAD

**Issue by caldeirav** [os-climate/os_c_data_commons#180]

**Comment by caldeirav** [comment]
When connecting into trino-secure-odh-trino.apps.odh-cl2.apps.os-climate.org from CloudBeaver, we get an Invalid Credentials exception:"

SQL Error: Authentication failed: Access Denied: Invalid credentials

**Comment by HumairAK** [comment]
@caldeirav can you try again? (trino password was incorrect for some reason)

**Comment by caldeirav** [comment]
@HumairAK it's all working fine now, thanks!
