### ISSUE TITLE
Get OSC deployments of trino working on version 388 and beyond

### ISSUE THREAD

**Issue by erikerlandson** [os-climate/os_c_data_commons#184]
I tried upgrading trino to version 388 this morning and broke trino on both osc1 and osc2 clusters.  Worse yet, CL2 is running trino 380 but CL1 crashes with 380 and is running 373.

We need to:
- get both clusters onto same version
- get the deployments running with latest (currently 388) to pick up new features and bugfixes we need.

**Comment by erikerlandson** [comment]
Here are trino coordinator logs from cl1 and cl2 I extracted while they were crashlooping:

[trino-coordinator-5fc849d755-pbg4b-trino-coordinator.log](https://github.com/os-climate/os_c_data_commons/files/9031454/trino-coordinator-5fc849d755-pbg4b-trino-coordinator.log)
[trino-coordinator-69cdb6ffd4-kjb2l-trino-coordinator.log](https://github.com/os-climate/os_c_data_commons/files/9031455/trino-coordinator-69cdb6ffd4-kjb2l-trino-coordinator.log)

**Comment by erikerlandson** [comment]
cc @MichaelTiemannOSC @caldeirav @HumairAK @rimolive

**Comment by MichaelTiemannOSC** [comment]
That would explain all the troubles I've been seeing trying to complete a simple notebook run on either CL1 or CL2.  Thanks!

**Comment by MichaelTiemannOSC** [comment]
Latest Trino is 392.  Has this issue been sorted?

**Comment by erikerlandson** [comment]
I managed to upgrade on my dev cluster, and I am ready to try it on cl1 to start with, then cl2.

the main issue was creating a new openshift secret named `trino-shared-secret` that defines an env var `TRINO_SHARED_SECRET`,
and then adding the following config:

`internal-communication.shared-secret=${ENV:TRINO_SHARED_SECRET}`
to both `config-coordinator.properties` and `config-worker.properties`

Last, you need to add this to the `Deployment`
```yaml
        envFrom:
            - secretRef:
                name: trino-shared-secret
```

**Comment by erikerlandson** [comment]
I'm going to close this since we have verified 388.  If we run into any future problems upgrading we'll open dedicated issue
