### ISSUE TITLE
Deploy IBM Fybrik on OSC Cluster 2

### ISSUE THREAD

**Issue by caldeirav** [os-climate/os_c_data_commons#187]

**Comment by Mohammad-nassar10** [comment]
Hi @HumairAK, can we set a meeting for working on the deployment of Fybrik on OS Climate cluster?
@roytman

**Comment by caldeirav** [comment]
Reference to deployment instructions: https://github.com/fybrik/fybrik/tree/master/integration/operate-first

**Comment by eoriorda** [comment]
@Mohammad-nassar10  Can we close this ticket as this has been deployed ?

**Comment by Mohammad-nassar10** [comment]
@eoriorda yes, thanks!

**Comment by eoriorda** [comment]
@caldeirav  Will ask the team if the cluster is working with Fabrik as expected.

**Comment by HeatherAck** [comment]
@caldeirav - team believes its deployed - is it working as expected
