### ISSUE TITLE
Create a Google account for OS-Climate to setup a data exchange with RiskThinking.ai

### ISSUE THREAD

**Issue by caldeirav** [os-climate/os_c_data_commons#188]

**Comment by caldeirav** [comment]
We need to create a Google Cloud account to trial the integration of RiskThinking.ai datasets through a BigQuery data exchange via

**Comment by HeatherAck** [comment]
Johnson Nguyen at LF is in the process of creating the Google account.  I've invited him to our GitHub:  jnguyen@linuxfoundation.org

**Comment by sternb0t** [comment]
Happy to help where I can on this one!

**Comment by MightyNerdEric** [comment]
We have the account set up. We can add owners and users to make use of the services. Costs will be billed to The Linux Foundation and passed through to the OS-Climate project.
Please email details on which Google accounts need access to eball@linuxfoundation.org.

**Comment by HeatherAck** [comment]
Thanks Eric.  @caldeirav Can you please share the specifics?

**Comment by eoriorda** [comment]
Complete and Eric is using
