### ISSUE TITLE
Need to onboard ESSD DBT catalog -> Open Metadata

### ISSUE THREAD

**Issue by MichaelTiemannOSC** [os-climate/os_c_data_commons#197]
I've done an initial rewrite of the ESSD pipeline to use DBT to create metadata suitable for OpenMetadata (following the example of the wri_gppd_powerplant_list).

I don't have admin privs, so need somebody who does to point the OpenMetadata ingestion scheduler at these files:

https://github.com/os-climate/essd-ingest-pipeline/blob/iceberg-dbt/dbt/essd_transform/target/manifest.json
https://github.com/os-climate/essd-ingest-pipeline/blob/iceberg-dbt/dbt/essd_transform/target/catalog.json

You can, of course, look at the iceberg-dbt branch of the whole repository.

If anything else is needed, please let me know!  If, as I hope, it's a good first draft, we have many other pipelines to convert!  I have not checked in the profiles.yml file as that file presently contains secrets.  I see there is a syntax that GitHub uses to pass GITHUB_TOKEN as a secret--could we teach that to DBT so that we can make it easier for people to check out a profiles.yml file that is "ready to go"?

@toki8 @mersin35 @HeatherAck

**Comment by caldeirav** [comment]
For the DBT metadata ingestion, there is a hitch: OpenMetadata only allows configuring one metadata ingestion per service, which means we can't pass catalog.json for multiple repos. Ideally I'd like to have one repo and one ingestion configured per schema with its own DBT catalog. I am checking with OpenMetadata folks if this is possible.

If not, I believe there is a way to perform an aggregation of DBT catalogs and manifests (this is something that enterprise may have to configure when they have many DBT projects), will check what is best practice here.

**Comment by MichaelTiemannOSC** [comment]
🤦 

I do hope we can aggregate catalogs and manifests without needing to spin up yet another major stack.  Why would it not be as simple as:

```
list_of_dicts = [dict_from_json(f) for f in catalog_files]
agg_dict = dict(chain.from_iterable(map(lambda d: d.items(), list_of_dicts])))
with open("catalog.json", "w") as f:
    dict_to_json (agg_dict, f)
```

?

**Comment by caldeirav** [comment]
Response from OpenMetadata team:

hi [@Vincent Caldeira](https://openmetadata.slack.com/team/U02P33BPCKD)
 currently we are allowing only one ingestion per service to be created. But what you are proposing is a valid usecase. Can you file a github issue we will ship it as part of 0.12 release

**Comment by MichaelTiemannOSC** [comment]
Shall I file the issue or do you want to?  I don't want to dirty it up with misunderstandings, but I think I can express the idea well enough...

**Comment by MichaelTiemannOSC** [comment]
Actually, see https://github.com/open-metadata/OpenMetadata/issues/5719

**Comment by caldeirav** [comment]
Issue filed at https://github.com/open-metadata/OpenMetadata/issues/6725

**Comment by MichaelTiemannOSC** [comment]
And now completed!  See https://github.com/open-metadata/OpenMetadata/pull/6737

This will make the 0.12 release very interesting to us!

**Comment by MichaelTiemannOSC** [comment]
Good news: OpenMetadata 0.12 is slated for release Sept 7th!

**Comment by MichaelTiemannOSC** [comment]
Version 0.12 has been released: https://github.com/open-metadata/OpenMetadata/releases/tag/0.12.0-release

**Comment by MichaelTiemannOSC** [comment]
I am making progress on ingesting ESSD into OM, but the pattern file to do so uses pachyderm, which seems to have disappeared:

```
_InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "DNS resolution failed for pachd.pachyderm.svc.cluster.local:30650: C-ares status is not ARES_SUCCESS qtype=A name=pachd.pachyderm.svc.cluster.local is_balancer=0: Domain name not found"
	debug_error_string = "UNKNOWN:DNS resolution failed for pachd.pachyderm.svc.cluster.local:30650: C-ares status is not ARES_SUCCESS qtype=A name=pachd.pachyderm.svc.cluster.local is_balancer=0: Domain name not found {created_time:"2022-09-30T13:54:15.436184-04:00", grpc_status:14}"
```

But now I have two problems: is this an ocs-ops question, a data commons question, a data-platform-demo question?

**Comment by caldeirav** [comment]
Re-running WRI-GPPD pipeline end to end now and I have no issue with the following pachyderm credentials:

# Pachyderm Credentials
PACH_ENDPOINT="pachd.pachyderm.svc.cluster.local"
PACH_PORT="30650"

Can you retry?

**Comment by MichaelTiemannOSC** [comment]
My mistake was running my notebook outside the cluster env, which has no route to necessary cluster resources.

I've now run both ingest and profiling but see neither metadata nor sample data.  I committed my changes before Hurricane Ian took out power and internet locally.  Logs are available in OpenMetadata instance (metadata_essd and profiling_essd).  Any help looking at those appreciated.

**Comment by caldeirav** [comment]
Corrected the metadata ingestion config for DBT as it was not using the raw path for the catalog and manifests stored on GitHub. Running again now.

![image](https://user-images.githubusercontent.com/23565280/193448366-f2285c62-2df1-4563-b505-aac958448894.png)

**Comment by MichaelTiemannOSC** [comment]
Tricky!  I had assumed that `https://github.com/os-climate/essd-ingest-pipeline/blob/iceberg-dbt/dbt/essd_transform/target/catalog.json` would have done the trick.  Thanks!

**Comment by caldeirav** [comment]
Looks like the ingestion worked now for some of the tables, eg.

![image](https://user-images.githubusercontent.com/23565280/193449655-487c5555-9149-4197-b754-cb6a11c9ca79.png)

**Comment by caldeirav** [comment]
However i see tables such as sectors for which it failed:

![image](https://user-images.githubusercontent.com/23565280/193449709-fbd75570-9ac4-4948-9111-9c0fd1fdcf7d.png)

**Comment by caldeirav** [comment]
From the manifest.json I don't see any obvious issue, may need to activate the logs there and see if we can understand what is happening.

**Comment by MichaelTiemannOSC** [comment]
We need a pretty-printer for the manifest before landing it to the filesystem!

**Comment by MichaelTiemannOSC** [comment]
I understand the issue.  I modified my version of the ESSD import to use the new `essd` schema and set `essd_table_prefix` to the empty string.  Due to the hurricane, I was not able to properly get those changes pushed in time, and when you re-ran the ingestion with the `mdt_sandbox` schema and the `essd_table_prefix` set to `essd_`, you created the correct metadata for the table `essd_sectors`.  I'll clean up the mess created by the weather and get a consistent metadata perspective of the right schema.  Thanks for the help!

**Comment by MichaelTiemannOSC** [comment]
And now really fixed after cleaning up the models subdirectory (and checking in changes to blow it away when we start building models from scratch).  Yay!

**Comment by MichaelTiemannOSC** [comment]
https://github.com/open-metadata/OpenMetadata/issues/7911
