### ISSUE TITLE
Support partitioning on fields that may contain whitespace (Trino 393)

### ISSUE THREAD

**Issue by MichaelTiemannOSC** [os-climate/os_c_data_commons#199]
Trino 393 fixed a bug just hit on the ESSD pipeline.  The fix is here https://github.com/trinodb/trino/issues/12226.  The ESSD workaround is here: https://github.com/os-climate/osc-ingest-tools/issues/38 (support tables with no partitions, when we cannot partition on fields that contain whitespace).

It also seems to roll up a lot of other nice fixes and functionality.  Let's monitor whether 394 cleans up any latent bugs or whether 394 mostly introduces new fixes/functions, and then update our own version accordingly.

In the past, @erikerlandson has been the keeper of the Trino updating process.  I'm assigning to @rynofinn on the assumption that it's now a "normal" updating request.  Please switch assignment to Erik if that's wrong.  And please let me know if all future such requests should go to Operate First queue instead of this one.

**Comment by HeatherAck** [comment]
per LF jira - Eric is working on this issue

**Comment by HeatherAck** [comment]
Received testing info.  Another blocker is being able to create an image.  @rynofinn needs Quay account.  Not a high priority, Also pending another Trino release for Google BigQuery bug.

**Comment by MichaelTiemannOSC** [comment]
@erikerlandson has completed the installation of Trino 398, which includes this fix.
