### ISSUE TITLE
Upgrade OpenMetadata to release 0.12

### ISSUE THREAD

**Issue by caldeirav** [os-climate/os_c_data_commons#202]

**Comment by caldeirav** [comment]
OpenMetadata just officially released version 0.12.0 (https://www.youtube.com/watch?v=FeT9Ia98g4Y). We require this release in order to finalise our data pipelines approach including the following fix:

https://github.com/open-metadata/OpenMetadata/issues/6725

Details about the latest release can be found at:

https://github.com/open-metadata/OpenMetadata/releases/tag/0.12.0-release

**Comment by HeatherAck** [comment]
Dependencies (requires upgrade to airflow, mysql, plus others)
No data needs to be preserved, can drop and re-create.
Want it completed ahead of NYC Climate Week **(Thurs AM, 15-Sep)**
@HumairAK to own task

**Comment by caldeirav** [comment]
OpenMetadata is working as expected and all metadata ingestion working fine. Moving to close this now.
