### ISSUE TITLE
Add CO2Signal data integration for CO2 Dashboard

### ISSUE THREAD

**Issue by caldeirav** [os-climate/os_c_data_commons#209]

**Comment by caldeirav** [comment]
CO2Signal API (https://www.co2signal.com/) provides access to where the electricity in a specific region comes from, how it was produced and how much carbon was emitted to produce it. We want to have hourly data stored in Data Commons to allow integration and analysis with Kepler streamed data.

**Comment by HeatherAck** [comment]
Use case:  real time data pipeline

**Comment by bryonbaker** [comment]
The implementation for this has been done. The code has been deployed in time for a demo @caldeirav is running next week. There is work to do to parameterise it and clean up a few things before I push it into the git repo.
The pipeline is available on the os-climate Kafka cluster in the co2signal topic. 
There are 30 zones in the pipeline and they are updated every hour. We need to purchase a subscription so we can increase the number of zones per hour and not be rate limited to one zone every 2 seconds.
At the moment we are using my eval API key - OS Climate needs to arrange getting its own key that we will store as a secret on the cluster. I will raise an issue to get that done.
This work has highlighted the need for us to think about naming conventions, use of kafka clusters, topics, etc so we can continue to implement more pipelines quickly

**Comment by HeatherAck** [comment]
will transfer from private repo to public; rate limited on number of zones (need to determine if paid access).  Need to better structure naming conventions; cleaning-up activities to be completed by 28-Oct (including ingestion pipeline locations).

**Comment by bryonbaker** [comment]
Further note - we need to think about the security architecture for the Kafka clusters. At the moment they are open to all namespaces in the lcuster.

**Comment by bryonbaker** [comment]
@HeatherAck - I think we move this to dine and create a separate issue for naming conventions as per above.

**Comment by HeatherAck** [comment]
created new issue - https://github.com/os-climate/os_c_data_commons/issues/237
