### ISSUE TITLE
Build dashboard for carbon emissions of OSC-Cluster2

### ISSUE THREAD

**Issue by caldeirav** [os-climate/os_c_data_commons#210]

**Comment by caldeirav** [comment]
Dependent on #209

**Comment by caldeirav** [comment]
The prometheus connector is working fine and I am able to get data. Need inputs from @rootfs and @husky-parul on the correct source.

SELECT 
	element_at(labels, 'cluster') as cluster,
	element_at(labels, 'container') as container,
	element_at(labels, 'pod_namespace') as pod_namespace,
	element_at(labels, 'pod') as pod,
	element_at(labels, '__name__') as name,
	element_at(labels, 'service') as service,
	element_at(labels, 'namespace') as namespace,
	element_at(labels, 'job') as job,
	element_at(labels, 'pod_name') as pod_name,
	element_at(labels, 'instance') as instance,
	timestamp,
	value
FROM uwm_prometheus."default".pod_energy_total 
where timestamp > (NOW() - INTERVAL '1' minute)

Output:

https://docs.google.com/spreadsheets/d/1Q1jImNCPfV1fA5tNsN3QedUB9aEFJUEU96SIgpAVVvA/edit?usp=sharing

**Comment by HeatherAck** [comment]
Vincent gave demo to 100 people - end to end wiring in place; regionalization of data is still needed; optimization/what if on running different IT loads at different times (currently monitoring use case).  Extracting data 1X per hour.  Vincent to investigate use of API with Watt Time (via Open Earth).

**Comment by caldeirav** [comment]
Closing this issue with first iteration of dashboard. Raising separate issues for improvements.
