### ISSUE TITLE
Trino client issue: "This result object does not return rows. It has been closed automatically"

### ISSUE THREAD

**Issue by caldeirav** [os-climate/os_c_data_commons#214]

**Comment by caldeirav** [comment]
Any read of results for requests that does not return rows returns an exception as follows:

"This result object does not return rows. It has been closed automatically."

To replicate, just need to run any non-SELECT statement and fetch the result, as done in many of our code samples as well as osc-ingest-tools:

# Execute table creation if the table does not exist
qres = engine.execute(tabledef)
print(qres.fetchall())

**Comment by MichaelTiemannOSC** [comment]
Probably a consequence of this: https://github.com/trinodb/trino-python-client/pull/220

The PR says that fetchall() is supposed to return the same results as before--no mention of complaining about no rows returned.  Need to file an issue upstream.  Will try to do later today.

**Comment by HeatherAck** [comment]
fixed per Michael
