### ISSUE TITLE
Open Metadata 0.13.1

### ISSUE THREAD

**Issue by HeatherAck** [os-climate/os_c_data_commons#223]
https://github.com/operate-first/support/issues/1114

**Comment by HeatherAck** [comment]
pending access to os-climate quay.  @erikerlandson to add for @redmikhail @ryanaslett @MightyNerdEric

**Comment by HeatherAck** [comment]
creator privileges granted

**Comment by bryonbaker** [comment]
Please also add @bryonbaker. I raised a gut issue on this a week or so ago. 
Thanks

**Comment by HeatherAck** [comment]
@MightyNerdEric updated images.  Has a pending pull request - https://github.com/operate-first/apps/pull/2722; Mikhail rolled back via ArgoCD when had issues last week.  @redmikhail to review pull request and make any comments.

**Comment by redmikhail** [comment]
With changes done by @MightyNerdEric and fix applied to Openmetadata DB version 0.13.1 has been deployed to the cluster 2. Testing of the deployment is in progress

**Comment by HeatherAck** [comment]
error when running essd data set.  @redmikhail is investigating

**Comment by HeatherAck** [comment]
profile_essd was always broken - but could perform open metadata ingestion which is now not working.  [failing to deploy]

**Comment by MightyNerdEric** [comment]
@MichaelTiemannOSC @caldeirav Looks like this is up and stable now. Any further issues before we close this out?
