### ISSUE TITLE
Access to quay.io/os-climate

### ISSUE THREAD

**Issue by bryonbaker** [os-climate/os_c_data_commons#249]
Need access to create a quay repo for the FX pricing and CO2 intensity images. 
At the moment these are being pulled from my private repo.

**Comment by bryonbaker** [comment]
@HumairAK 
Is this something you can arrange?

**Comment by HumairAK** [comment]
@bryonbaker I don't have access to this repo. I think @erikerlandson does

**Comment by bryonbaker** [comment]
@erikerlandson - is this something you can help with?

@HeatherAck - FYI re issue #223

**Comment by redmikhail** [comment]
`bryonbaker` user was added to `osclimate` team in os-climate org on Quay with creator privileges

**Comment by bryonbaker** [comment]
Got it thank you.
