### ISSUE TITLE
Template for Data Pipelines

### ISSUE THREAD

**Issue by caldeirav** [os-climate/os_c_data_commons#253]

**Comment by caldeirav** [comment]
Creation of a clean base template for developers creating a new data pipeline, under https://github.com/os-climate/data-pipeline-template. The template should have the base structure for data, metadata and quality tests ingestion (via DBT and great_expectations integration with OpenMetadata).

**Comment by MichaelTiemannOSC** [comment]
Quick note that the python version should be at least 3.9, not 3.8 (as stated in Pipfile).  There are several other minimum versions we should stipulate.  See #234.

**Comment by caldeirav** [comment]
Template has been completed for extraction / load / transform. Remaining to be tested is integration with OpenMetadata which is now failing due to integration with Airflow Managed APIs. Will proceed to close this issue and open new issues for additional work.
