### ISSUE TITLE
Create two namespaces on odh-cl2

### ISSUE THREAD

**Issue by bryonbaker** [os-climate/os_c_data_commons#255]
Can I please get a namespace created on cl2 to run some secrets experiments?

Namespace name: vault-dev

**Comment by bryonbaker** [comment]
@caldeirav - FYI

**Comment by HeatherAck** [comment]
Reassigning to @ryanaslett and adding @redmikhail to provide any support required

**Comment by redmikhail** [comment]
It seems that this task is more suited for cluster 1 , resulting solution can be subsequently propagated to cluster 2

**Comment by bryonbaker** [comment]
Namespaces have been created. Thanks. Closing this issue now.
