### ISSUE TITLE
dbt profiles.yml file contains secrets

### ISSUE THREAD

**Issue by MichaelTiemannOSC** [os-climate/os_c_data_commons#259]
The dbx profiles.yml file contains JWT secrets, but it should not (see #183).  The docs should reflect how to reference secrets without putting them in the file.  Otherwise, profiles.yml is a security problem waiting to happen.

The doc pages to fix are: https://github.com/os-climate/os_c_data_commons/blob/main/docs/data-transformation.md and https://github.com/os-climate/os_c_data_commons/blob/main/docs/profiles.yml (the latter casually invites users to simply store secrets in this file, rather than showing how to not store secrets in the file).

**Comment by caldeirav** [comment]
Not sure I understand your comment here. I use profiles.yml exactly as I use credentials.env (it is out of any Git repository) and therefore there is no sharing of secret. As recommended by Bryon we can also add this into gitignore for additional protection and therefore secrets will not be shared.

This is for dev and of course for a production workload the secret would have to be injected. If there's a better method, feel free to contribute an example.

**Comment by MichaelTiemannOSC** [comment]
My comment is that if there is ONE file that contains secrets, people (and github) can know to be careful about it.  But the proliferation of secrets across multiple files is the road to ruin.  I see that YAML does have a standard way to pull secrets from the environment.  This is the pattern I'm looking for, but I don't know whether its based on something specific to Helm or something general in YAML: https://stackoverflow.com/questions/68364968/helm-add-secrets-from-another-yaml-file (and of course credentials.env is not YAML, but I'm sure there's a way to bridge that gap, too).

**Comment by bryonbaker** [comment]
I am (slowly) working through how we can do this with Hashi Vault. I am up to experimenting with airflow and Jupyter. 
The model will be simple enough. The namespace has a service account that entitles workloads to retrieve secrets programmatically, or we can annotate the workloads so the secret is mounted as a volume when the workload starts. This is the model I think would be best. 
I need a couple of more weeks as I have a ton of stuff going on ATM. 
Note, there is a secrets operator already that could probably also inject the secret based on annotations. I need to learn about that some more. 
Then I think we can pull together some architectural options for joint consideration and choice.

**Comment by MichaelTiemannOSC** [comment]
It appears there is an `env_var` function that we should work into our documentation.  Using env_var is confirmed by the dbt community to be a good way to avoid the toxic consequences of putting (and maintaining) secrets in YAML files: https://getdbt.slack.com/archives/CBSQTAPLG/p1647538347999199
