### ISSUE TITLE
OSC-Platform-013: Running GPU workloads

### ISSUE THREAD

**Issue by caldeirav** [os-climate/os_c_data_commons#26]
As a developer on the corporate data pipeline, I need to access GPU to run the NLP code

**Comment by caldeirav** [comment]
GPUs are now available on the cluster, Erik is planning to create a notebook image with GPU enabled as example. Once available / tested we can close this item.

**Comment by MichaelTiemannOSC** [comment]
I've added a high priority label to this item as the NLP team is blocking on notice that their GPU workload is ready to proceed.

**Comment by erikerlandson** [comment]
We have verified that jupyter notebooks can access the gpu resources on the cluster, so I am closing.
