### ISSUE TITLE
new schema request: rmi

### ISSUE THREAD

**Issue by MichaelTiemannOSC** [os-climate/os_c_data_commons#264]
I'd like to request authorization for a new schema named `rmi` on CL2.  Initially I will be the owner and it can be public read access.  In the future I hope to invite members from the RMI Transition Utilities Data Hub to become contributors and perhaps administrators of data present in this schema.  In the meantime, I'd doing RMI data pipeline development in `mdt_sandbox`.

Thanks!

**Comment by MichaelTiemannOSC** [comment]
Ping, adding @redmikhail

**Comment by ChristianMeyndt** [comment]
Hi @erikerlandson ,
I get again a TrinoUserError(type=USER_ERROR, name=TABLE_NOT_FOUND, ...) whenever I try to access one of the PCAF tables. General connection to trino works with my credentials.
Is there a self-service for trino access or how is it maintained?
cc @MichaelTiemannOSC , @redmikhail

**Comment by MichaelTiemannOSC** [comment]
The original issue was about creating the RMI schema, which was done.  The issue reported by @ChristianMeyndt relates to configuration parameters for the `pcaf_sovereign_footprint` schema, a different animal.  @erikerlandson should be able to help resolve Christian's instant problem.  We are in the process of creating an entirely new trino world based on the DataMesh pattern, and I don't know the answer to how that's going to work (yet).

**Comment by HeatherAck** [comment]
pinging @erikerlandson

**Comment by erikerlandson** [comment]
This issue was resolved.  If there are different errors they should go on other issues.
