### ISSUE TITLE
Upgrade Trino on cl1 to match version deployed on cl2

### ISSUE THREAD

**Issue by redmikhail** [os-climate/os_c_data_commons#266]
upgrade both clusters to  397 (@redmikhail to verify)

**Comment by HeatherAck** [comment]
@redmikhail still working on this - planned for wk of 13-Mar

**Comment by HeatherAck** [comment]
@redmikhail to finish on 21-Mar

**Comment by HeatherAck** [comment]
to complete week of 27-Mar

**Comment by HeatherAck** [comment]
@ryanaslett to work on week of 17-apr

**Comment by HeatherAck** [comment]
@ryanaslett to work on week of 24-apr

**Comment by HeatherAck** [comment]
4.14 version would be useful relative to iceberg corruption we experienced in the past

**Comment by HeatherAck** [comment]
@redmikhail to own the upgrade to Trino 419 - week of 12-June

**Comment by HeatherAck** [comment]
will be done week of 19-June

**Comment by MightyNerdEric** [comment]
It took a few days, but Trino on cl1 is now in a working state with v398 (we still have one more commit to merge, but it's currently running with a manual override of the same config). Once that last PR is merged, barring any regressions, this can be closed and we can move on with #171.

**Comment by MightyNerdEric** [comment]
With the PR merged, Trino on cl1 is at v398 and working as expected. This issue can be closed.

**Comment by ModeSevenIndustrialSolutions** [comment]
See: 
https://github.com/os-climate/ops-argocd
