### ISSUE TITLE
Access request for S3 Buckets

### ISSUE THREAD

**Issue by mvarfima** [os-climate/os_c_data_commons#269]
Hi,

I requested s3 access at https://github.com/os-climate/OS-Climate-Community-Hub/issues/78 . But after recieving my aws credentials I'm having credential error when trying to access the bucket. You can see more details in the issue #78 of OS-Climate-Community-Hub and it may be releated to R/W permission.

Please, could you considere taking a look at this issue? Thanks in advance.

**Comment by mvarfima** [comment]
Hi,

sorry for the delay but github did not notify your message to my email.

Yes, I can access that link and view the new keys but... I now have a new error: "Acess denied".

**Comment by mvarfima** [comment]
Hi,

the problem was solved after reinstalling s3fs.

Thank you so much!

**Comment by HeatherAck** [comment]
@mvarfima ok to close?

**Comment by mvarfima** [comment]
Yes please, thank you so much.
