### ISSUE TITLE
Provision/configure cluster to host Operate First migrated services

### ISSUE THREAD

**Issue by HeatherAck** [os-climate/os_c_data_commons#275]

**Comment by HeatherAck** [comment]
see also https://github.com/os-climate/os_c_data_commons/issues/270

**Comment by HeatherAck** [comment]
@redmikhail will have admin cluster operational by 20-Mar

**Comment by redmikhail** [comment]
ROSA (Red Hat Openshift Service on AWS) cluster has been provisioned, https://console-openshift-console.apps.osc-cl3.eqcq.p1.openshiftapps.com , authentication is using GitHub as IDP. Initial cluster setup uses OCP version 4.10.54 , has three workers based on m5.2xlarge machines (master and infra node setup is managed by the ROSA control plane and can not be adjusted) . Cluster is configured as multi availability zone cluster (all nodes spread across three zones in us-east-1 region )
