### ISSUE TITLE
Create repositories for artifacts required for Operate First migrated services (example App of Apps for ArgoCD)

### ISSUE THREAD

**Issue by HeatherAck** [os-climate/os_c_data_commons#277]

**Comment by HeatherAck** [comment]
see also https://github.com/os-climate/os_c_data_commons/issues/270

**Comment by HeatherAck** [comment]
@ryanaslett to create repo: ops-ArgoCD and add yamls, yaml for ArgoCD config (yaml for a yaml).  create subdirectories as we go.   include permissions for Ryan Cook

**Comment by HeatherAck** [comment]
repo created for ops-ArgoCD; created sys admin group in github

**Comment by ryanaslett** [comment]
https://github.com/os-climate/ops-argocd has been created, and a sysadmin team (https://github.com/orgs/os-climate/teams/infrastructure-admins) has been built to give access to it.
