### ISSUE TITLE
Move ArgoCD OSC related applications from Operate First server as is

### ISSUE THREAD

**Issue by HeatherAck** [os-climate/os_c_data_commons#279]

**Comment by HeatherAck** [comment]
see also https://github.com/os-climate/os_c_data_commons/issues/270

**Comment by HeatherAck** [comment]
plan to work on 27-mar

**Comment by HeatherAck** [comment]
finalize the re-pointing to os-climate repository - some of the pointers did not get moved during merge.  @redmikhail will clean-up, synch issues

**Comment by HeatherAck** [comment]
@redmikhail please confirm if done

**Comment by redmikhail** [comment]
Auto-sync is enabled on majority of the applications. Cleaned up residues of the references to Gregory temporary fork
