### ISSUE TITLE
OSC-Platform-015: Migration / Execution of Allianz NLP code

### ISSUE THREAD

**Issue by caldeirav** [os-climate/os_c_data_commons#28]
As an Allianz NLP developer, i want to execute my notebook code (https://github.com/os-climate/corporate_data_pipeline/tree/main/Allianz_NLP) on the JupyterHub platform.

**Comment by MichaelTiemannOSC** [comment]
Added Ismail Demir as the changes required to run in ODH environment requires adaptation of originally authored code.

**Comment by erikerlandson** [comment]
cc @JeremyGohBNP

**Comment by erikerlandson** [comment]
for simply developing code and testing it in jupyter, the pipeline image build is not necessary, so development can start with the current environment.

**Comment by caldeirav** [comment]
@ChristianMeyndt except for maybe performance issues, can we close this issue since the model has been deployed and working?

**Comment by ChristianMeyndt** [comment]
Yes, you can close this ticket. We are generally able to run the code in JupyterHub.
Of course there are still todos esp. for the training of models, but this will be handled within other issues.
