### ISSUE TITLE
Provision/configure HashiCorp Vault , grant access

### ISSUE THREAD

**Issue by HeatherAck** [os-climate/os_c_data_commons#280]

**Comment by HeatherAck** [comment]
see also https://github.com/os-climate/os_c_data_commons/issues/270

**Comment by HeatherAck** [comment]
pending cluster creation

**Comment by HeatherAck** [comment]
cluster created.  work in progress - week of 27-Mar

**Comment by Gregory-Pereira** [comment]
Vault sso documentation: https://github.com/Gregory-Pereira/Vault-SSO-for-Openshift/tree/document-vault-and-vault-oidc-setup
Op1st vault docs: https://github.com/operate-first/apps/tree/master/docs/content/vault_eso/docs

**Comment by HeatherAck** [comment]
@MightyNerdEric verified working.
