### ISSUE TITLE
Migrate HashiCorp Vault secrets

### ISSUE THREAD

**Issue by HeatherAck** [os-climate/os_c_data_commons#281]

**Comment by HeatherAck** [comment]
see also https://github.com/os-climate/os_c_data_commons/issues/270

**Comment by HeatherAck** [comment]
plan to work on 27-mar

**Comment by Gregory-Pereira** [comment]
New vault instance: https://vault-ui-vault.apps.osc-cl3.eqcq.p1.openshiftapps.com
Old vault instance: https://vault-ui-vault.apps.smaug.na.operate-first.cloud/

**Comment by MichaelTiemannOSC** [comment]
I was able to navigate to GitHub as a method in the Other category, but then it requested me to enter my GitHub token.  All other GitHub auth I've done makes this transparent (somehow authenticating from Chrome and/or FireFox).  It seems wrong to me to enter my GitHub token into a non-GitHub site.

**Comment by Gregory-Pereira** [comment]
Yes, use the OIDC login method. The reason we use this is because it hooks into the kubernetes cluster authentication which in turn authenticates with github.

**Comment by MichaelTiemannOSC** [comment]
OK, so I did the non-intuitive thing of clicking on something I've never clicked on before, it opened a window I have seen before asking me to use a GitHub ID, which then took me to a dialog to authorize a new token, which I accepted.  I could then gain access to the vault, but I saw no secrets (cubby was empty).

**Comment by Gregory-Pereira** [comment]
Closing issue as it was confirmed secrets have been properly migrated as of last hack session.
