### ISSUE TITLE
Install Keycloak

### ISSUE THREAD

**Issue by HeatherAck** [os-climate/os_c_data_commons#285]
Need info for roles/permissions

**Comment by HeatherAck** [comment]
@MightyNerdEric get installation done; @HeatherAck will set up meeting to define roles/groups/access permissions/etc.

**Comment by HeatherAck** [comment]
@HeatherAck to set up mtg in afternoon. but not pre-req for install itself

**Comment by HeatherAck** [comment]
@MightyNerdEric reviewing steps to install Keycloak to properly work with open shift cluster.  On pace to install this week (15-May)

**Comment by MightyNerdEric** [comment]
Keycloak is installed on CL3, but this is just the initial step. I need to add a production-ready database container, and then write the config out to our ops-argocd repo. I'll be off the next couple days (June 2 & 5), but will resume work where I've left off as soon as I return.

**Comment by HeatherAck** [comment]
For week of 12-Jun:  need to get production db connected to it, plus a few other tasks - need to be added to ArgoCD.

**Comment by HeatherAck** [comment]
had issues with another project.  will prioritize this week.  need to try it out as operator (operator installed, needs to be deployed). @MightyNerdEric to update issue on Friday will status

**Comment by MightyNerdEric** [comment]
I have not been able to spin up a stable Keycloak deployment using the operator. The other system has been ready for weeks, but I was tasked with comparing the two. So here is the result of my comparison: given the same configuration values, the manual setup (which will never be manual again, as we're going to put it into code) gave us a solid, stable system, and the operator did not. So we will move forward with the initial config. I will push the change for ops-argocd on Monday.

**Comment by MightyNerdEric** [comment]
Quick update on this: the PR for the code change is open, but not quite complete. I'm still squishing a few bugs, but most of the components seem to be working as intended. I expect this to be done by EOW.

**Comment by HeatherAck** [comment]
Keycloak not coming up due to postgres issue where it won't load.  Need to address postgres issue - maybe an init file issue, possibly not being run as root.  If cannot get to run easily, need to transition to running it as operator [also being used as data mesh pattern].  See example:  https://github.com/opendatahub-io-contrib/data-mesh-pattern/tree/main/gitops/keycloak/overlays

Most recent one:  https://github.com/keycloak/keycloak/tree/main/operator

**Comment by HeatherAck** [comment]
pending code reviews - @redmikhail started review.  postgres not working.  will propose PR tomorrow morning to @MightyNerdEric branch. would like to use operator. installed in local env.  goal is to push to main week of 31-Jul

**Comment by HeatherAck** [comment]
closed - but @redmikhail will create a new issue(s) to set up users, plus config and setup between data exchange and data commons
