### ISSUE TITLE
Access request for S3 Buckets

### ISSUE THREAD

**Issue by toby944** [os-climate/os_c_data_commons#294]
Hello, 

Is it possible to have access and keys for the ITR pipeline, particularly for the ITR-data-production.ipynb file ? 

![image](https://user-images.githubusercontent.com/127318811/231293933-7d34310c-22b0-4c33-baf3-bbc79ffe010b.png)

I am trying to access some of the emission and target data for companies.

Many thanks in advance. 

Kind regards, 

Toby

**Comment by HeatherAck** [comment]
@ryanaslett - can you please provide Toby access credentials?

@MichaelTiemannOSC - can you please share info on how to access the ITR data you've curated with Toby?

**Comment by toby944** [comment]
Hello, many thanks for your reply. I was just wondering if there were any updates regarding the access credentials? Thank you for your help, Toby

**Comment by MichaelTiemannOSC** [comment]
It appears that access credentials were sent.
