### ISSUE TITLE
Leftover of Op1st migration

### ISSUE THREAD

**Issue by Gregory-Pereira** [os-climate/os_c_data_commons#295]
This issue should track the leftover elements of the op1st migration that will need to be picked up by the OSC team.

AICOE Pipelines: We discussed there were pipelines for building jupyter notebooks. I think they were ran on smaug on the `opf-ci-pipelines` namespace, could someone take a look and verify these are the correct ones?
    - ns: https://console-openshift-console.apps.smaug.na.operate-first.cloud/k8s/ns/opf-ci-pipelines/pods
    - argocd app: https://github.com/operate-first/apps/blob/1a2f3ab86136949023f65975b7430a5e447d0d9e/argocd/overlays/moc-infra/applications/envs/moc/smaug/operate-first/prod-aicoe-ci.yaml
    - AICOE code: https://github.com/AICoE/aicoe-ci/tree/master/manifests/overlays/moc
    
Read only argocd: 
 - Some elements were already moved over but some remain so this remains incomplete. starting with the reference PR: https://github.com/operate-first/apps/pull/741/files. Be careful however as there are some core differences of how I setup the OSC environment vs op1st was setup. 
 - Differences / issues
---------------------------
1. Openshift Gitops uses cluster authentication but in op1st we also used Dex for authentication which in turn used cluster-authentication. This 2 step allowed us to created different sets of access. (see [op1st argocd Dex config](https://github.com/operate-first/apps/blob/master/argocd/overlays/moc-infra/configs/argo_cm/dex.config))
2. In op1st, argocd "deployed itself". What i mean by this is argocd created an application of itself to track all the related groupings and manifests (see [op1st argocd application of argocd itself](https://github.com/operate-first/apps/blob/master/argocd/overlays/moc-infra/applications/envs/moc/infra/cluster-management/argocd.yaml)). This worked because we used a base install of the manifests, ie. we had nothing managing the "application" but argocd. But your team uses openshift Gitops operator which manages the argocd instance, ergo if you created an application for argocd it would fight with the operator. There for you need to find some other way to deploy this. An example I took is to deploy the argocd RBAC in OSC as its own application, see example: https://github.com/os-climate/ops-argocd/blob/main/argocd/overlays/osc-cl3/applications/envs/osc/osc-cl3/default/argocd-rbac.yaml. I originally planned to do [the same thing](https://github.com/os-climate/ops-argocd/blob/main/argocd/overlays/osc-cl3/applications/envs/osc/osc-cl3/default/argocd-clusters.yaml) with your argocd clusters, but ultimately I resolved it how native argocd does by just plugging it in because it doesn't really change.
---------------------------
- Aside from these two issues what needs to be done:
---------------------------

1. Create argocd readonly group
2. make sure groups and RBAC for group are deployed / managed somehow 
3. make a policy for readonly group (see [how this is done in op1st](https://github.com/operate-first/apps/blob/f36c83bd752d4583974863960c3becc01ec92d4c/argocd/overlays/moc-infra/configs/argo_rbac_cm/policy.csv))
4. Test and make sure everything works
---------------------------

/assign @redmikhail 
/assign @ryanaslett

**Comment by HeatherAck** [comment]
@redmikhail and @ryanaslett to finish week of 24-Apr

**Comment by HeatherAck** [comment]
@ryanaslett to check with @redmikhail on next steps

**Comment by HeatherAck** [comment]
@redmikhail:  some argo CD apps not auto-synching (5 remain) - SOSTrades - this is done; permissions issue still open (still need to create read only and then create app specific permissions).  Need to align on naming convention and trial it on first app - PhysRisk. @HeatherAck to let Matt know will discuss on Thursday, 25-May

**Comment by HeatherAck** [comment]
Need to pull some of the documentation from operate first.  Need a new issue for each project to have a documented on-boarding process for new users their workstream.

**Comment by HeatherAck** [comment]
@redmikhail to move to Ready

**Comment by HeatherAck** [comment]
still need to enable users to manage the own app in ArgoCD - but will be separate issue.
