### ISSUE TITLE
Security Issue Management:  Set the proper 'alternate contacts' for the aws account

### ISSUE THREAD

**Issue by HeatherAck** [os-climate/os_c_data_commons#298]
Ensure that LF incident management as well as security-incident-notification@lists.os-climate.org are on the AWS account

**Comment by HeatherAck** [comment]
![Image](https://user-images.githubusercontent.com/90428947/233450594-61eae45e-b7eb-4f45-9028-98e81ecb2d97.png)

**Comment by MightyNerdEric** [comment]
In terms of alternative contacts, this is complete. Security emails will go to the security email list. Members of that mailing list will need to selectively escalate incidents to the security-incident-notification list (outside users can also directly report incidents to this list). I'll work on getting more non-US time zone engineers on the list, but this is the proper channel security-related comms.
