### ISSUE TITLE
Rate limit exceeded error

### ISSUE THREAD

**Issue by HeatherAck** [os-climate/os_c_data_commons#305]
Rate limit exceeded Open Shift

**Comment by HeatherAck** [comment]
![Image](https://user-images.githubusercontent.com/90428947/234701316-343657be-072c-4c0a-80e5-5a0019fe3a21.png)

**Comment by HeatherAck** [comment]
David ran into a rate limit exceeded error again.  [aicos-osc-demo · Details · Red Hat OpenShift Container Platform (os-climate.org)](https://url.emailprotection.link/?bfuWSLMRIWjDBrWABQ5p6jkgNBN05VZ0mEesVvudAGI5CWxddOsnuY5Ffo1yp7B044cB_9LO7dzFrh8_03Pdk7AjKRIx8eePJGmhCRQd398lAsCZmHYsOifyCFIeG_-esm6hleE1W8NVBD9GOVFuBuD6ku-Anez8PYmPeDRcu-kI~)

**Comment by MightyNerdEric** [comment]
@DaBeIDS ran into this? Can you please provide details on recreating the error?

The Github rate limit is only 60 requests per hour from an unknown IP, but 5000 for any verified user. If we can get this service to use an API key to make these requests as an authenticated user, the rate limit should not be an issue.

**Comment by MightyNerdEric** [comment]
With no further issues reported, I'm going to close this as Resolved.

**Comment by DaBeIDS** [comment]
Hey Eric, thanks a lot. Yes there are no further issues up to now with that.
Best regards,
David
