### ISSUE TITLE
Add gitignore to every main branch

### ISSUE THREAD

**Issue by HeatherAck** [os-climate/os_c_data_commons#307]
Prevent credentials from being committed

**Comment by HeatherAck** [comment]
See: https://github.com/os-climate/data-pipeline-template/pull/1/files
and https://github.com/os-climate/data-science-template/blob/master/.gitignore

**Comment by HeatherAck** [comment]
@MightyNerdEric to show @HeatherAck commands to push directly to main.

**Comment by MightyNerdEric** [comment]
This was completed in May.
