### ISSUE TITLE
Trino Error

### ISSUE THREAD

**Issue by HeatherAck** [os-climate/os_c_data_commons#308]
Member having trouble accessing Trino

**Comment by HeatherAck** [comment]
@erikerlandson can you please troubleshoot:
 
From @mersin35 

I get an error message when I try to execute the command below. I believe some of my rights are revoked. I try to merge my changes with the latest changes done by you…

 

create_trino_table_and_dbt_metadata(ingest_table, df, ['country_iso_code'], custom_meta_content, custom_meta_fields, verbose=True)


OperationalError: (trino.exceptions.TrinoExternalError) TrinoExternalError(type=EXTERNAL, name=HIVE_METASTORE_ERROR, message="Got exception: java.nio.file.AccessDeniedException s3a://redhat-osc-physical-landing-647521352890/trino/ingest/ingest_temp_a5a93733: getFileStatus on s3a://redhat-osc-physical-landing-647521352890/trino/ingest/ingest_temp_a5a93733: com.amazonaws.services.s3.model.AmazonS3Exception: Forbidden (Service: Amazon S3; Status Code: 403; Error Code: 403 Forbidden; Request ID: ***********************; S3 Extended Request ID: bssE/vu8mJHM/6MZdoV7KwU5MQx8xxOctfemPvJIWFMyI1Jp6lUEmjeaReDR9lU3hDN8rzq/Aco=), S3 Extended Request ID: bssE/vu8mJHM/6MZdoV7KwU5MQx8xxOctfemPvJIWFMyI1Jp6lUEmjeaReDR9lU3hDN8rzq/Aco=:403 Forbidden", query_id=20230504_082759_00055_pfint)

[SQL: create table if not exists osc_datacommons_hive_ingest.ingest.ingest_temp_a5a93733 (

    rec_source varchar,

    data_provider varchar,

    country_name bigint,

    validity_date integer,

    attribute varchar,

    value double,

    value_units varchar,

    country_iso_code varchar

) with (

    format = 'parquet',

    partitioned_by = array['country_iso_code'],

    external_location = 's3a://redhat-osc-physical-landing-647521352890/trino/ingest/ingest_temp_a5a93733/'

)]

(Background on this error at: [https://sqlalche.me/e/14/e3q8](https://url.emailprotection.link/?b0km1xcj82Bzz-cY6gaixT_k2FHfLFWHc39QzJaVJy6JERR8YDopZmYUScH7U62GhUIX0UrYrjvXH3Zo8ZmZCP_uzR8vJnehHm2ZW9IAvniC5m7gw3uNJnAmyTgLXOTq0))

**Comment by erikerlandson** [comment]
Looks like it may be a problem with the s3 bucket credentials.  @redmikhail  are you aware of any changes to the physical landing bucket creds?
