### ISSUE TITLE
Add new users to aicoe-osc-demo

### ISSUE THREAD

**Issue by HeatherAck** [os-climate/os_c_data_commons#317]
Please give the other four access to the open-shift cluster “/ns/aicos-osc-demo” as I have. The github accounts are

 

Max: mriefer

Ismail: idemir-ids

Christian: ChristianMeyndt

Tobias: tobias-watzel

**Comment by redmikhail** [comment]
It is done (PR12 ) . Please let me know if there are any issues

**Comment by ChristianMeyndt** [comment]
Hi @redmikhail ,
In only see other projects but not aicoe-osc-demo:
![image](https://github.com/os-climate/os_c_data_commons/assets/69670279/f6222d05-8ac1-4dbc-bd5a-2a176bd2f8a8)
Seems this only affects me. Can you please check again.

**Comment by ChristianMeyndt** [comment]
Hi @redmikhail ,
I still don't see the project aicoe-osc-demo.
Please check again.
