### ISSUE TITLE
Update Openmetadata from version 0.13.1 to 1.0.5

### ISSUE THREAD

**Issue by redmikhail** [os-climate/os_c_data_commons#321]

**Comment by HeatherAck** [comment]
CL1 is nearly complete - one open issue (airflow / db connection not working).  Goal to finish CL1 on 24-Jul.  Will work on CL2 week of 24-Jul (will be user impacting) and will notify broader org.

**Comment by redmikhail** [comment]
Upgrade is completed with https://github.com/os-climate/ops-argocd/pull/27 . Additional improvement to enable backup for openmetadata  database is tracked as https://github.com/os-climate/os_c_data_commons/issues/325
