### ISSUE TITLE
Upgrade Trino on CL1 and CL2 to latest version

### ISSUE THREAD

**Issue by HeatherAck** [os-climate/os_c_data_commons#323]
Upgrade Trino to 422

**Comment by MightyNerdEric** [comment]
Related issues: #234, #171, #252

**Comment by HeatherAck** [comment]
@MightyNerdEric will complete the week of 31-Jul (dedicating 3 of next 4 days to task)

**Comment by HeatherAck** [comment]
still in progress

**Comment by HeatherAck** [comment]
code change will be finished today then will perform testing (completed review of release notes - making hive changes, etc.)

**Comment by HeatherAck** [comment]
code change merged.  image has not updated.  redeployed with wrong image.  investigating problem.

**Comment by HeatherAck** [comment]
updated pointer to os-c; worker pods getting error in CL2 (CL1 is fine); rolled back - @MightyNerdEric will debug but will reach out to @redmikhail on Friday.

**Comment by MightyNerdEric** [comment]
The issue with CL2 was the (undocumented) requirement that the Trino image have the jmx_exporter added to it. I've updated the image, and everything is working as expected now. I'm going to add this to the operations repo, but that does not directly affect this. This issue can be closed.
