### ISSUE TITLE
define how to obtain a view of the materialized source using DBT

### ISSUE THREAD

**Issue by HeatherAck** [os-climate/os_c_data_commons#336]

**Comment by MichaelTiemannOSC** [comment]
Marius, there are a few issues that are pre-requisites to this, and some that will depend upon it, but for now, this will be a good proxy and tracker issue for the overall collection of data mesh federation progress.  Can you please keep it updated with research questions, progress, blockers, etc.?

One near-term pre-requisite will be the creation of a repository to contain the DBT project necessary to effect the transformations we discussed.  That repo may well satisfy other prerequisites of other related issues.

@toki8 @HeatherAck

**Comment by HeatherAck** [comment]
duplicate to #328
