### ISSUE TITLE
OSC-Platform-016: Validation of pipeline architecture with PUDL data

### ISSUE THREAD

**Issue by MichaelTiemannOSC** [os-climate/os_c_data_commons#34]
The PUDL project transforms regulatory utilities data (capacity, generation, fuel, emissions, location, ownership, etc) into *frictionless* and *tidy* data.  PUDL is the principal part (but not fully stand-alone) of this GitHub site: https://github.com/catalyst-cooperative.  See new release: https://github.com/catalyst-cooperative/pudl/releases/tag/v0.4.0

PUDL has a layered data architecture: Python data scrapers, Zendo storage, sqlite databases, datasette feeding Read The Docs and data dictionaries, Dask/Parquet feeding Jupyter Notebooks, etc.

A snapshot of the PUDL data has been loaded into AWS Athena database for use by our V1 Data Browser.  With proper coordination with their project, we could make the Data Commons Platform a first-class target for their system, which would give us exemplary data for US-based power plants that would set a technical standard for European and Asian utilities data projects to follow.

Suggested first step would be for Marcel Hild and @erikerlandson  to discuss with PUDL lead Zane Selvans  (zane.selvans@catalyst.coop) how we might make this work, with @MichaelTiemannOSC and @toki8 supporting.

**Comment by caldeirav** [comment]
@redmikhail as discussed with you we are still facing issues to access arn:aws:s3://dev-osc-physical-landing-309737258120/ which Michael / Madhu Bussa are looking at.

**Comment by MichaelTiemannOSC** [comment]
I believe I have fixed the problem so that a power user can copy from the physical risk landing zone to the Red Hat data world:

`aws s3 cp --profile 647521352890_AWSPowerUserAccess s3://dev-osc-physical-landing-309737258120/datacommon-physicalrisk-landing/wri-pp/wri-pp.tsv s3://ocp-odh-os-demo-s3/data/WRI-upload/`

Please let me know if you have any further problems.

**Comment by caldeirav** [comment]
It is now working. Output as follows:

aws s3 ls --profile 647521352890_AWSPowerUserAccess s3://dev-osc-physical-landing-309737258120 
                           PRE athena_result/
                           PRE csv/
                           PRE datacommon-physicalrisk-landing/
                           PRE dev-osc-physicalrisk-upload/
                           PRE pudl-0.4.0/
2021-09-05 07:13:23 6367065260 pudl-v0.4.0-2021-08-17.tgz

**Comment by caldeirav** [comment]
With the latest commit on https://github.com/os-climate/data-platform-demo/blob/master/notebooks/pudl_ingestion_sample.ipynb we have now validated the proposed ingestion approach for PUDL data.

@MichaelTiemannOSC I propose we should now create a dedicated repo for PUDL data ingestion and start to manage issues at a more detailed level there.

**Comment by caldeirav** [comment]
Closed as discussed in sprint meeting
