### ISSUE TITLE
add new team members in sostrades-transition-risk

### ISSUE THREAD

**Issue by sostrades-pjbarjhoux** [os-climate/os_c_data_commons#364]
Hi,

Could it be possible to add these github accounts to sostrades-transition-risk team please?
https://github.com/orgs/os-climate/teams/sostrades-transition-risk

naiksushrita
bagalnilesh
jannudeepthi

**Comment by HeatherAck** [comment]
@eharrison24 - can you please add to odh and the sostrades team?

**Comment by sostrades-pjbarjhoux** [comment]
I can't see these github accounts on osclimate organization, could you please help me to add them? thanks

**Comment by strawberry-baked-alaska** [comment]
@HeatherAck @sostrades-pjbarjhoux - Invites have been sent! Let me know if you need anything else.
