### ISSUE TITLE
Logs in OpenShift platform unauthorized

### ISSUE THREAD

**Issue by joemoorhouse** [os-climate/os_c_data_commons#367]
When viewing logs for Pods where previously we saw log messages we now see the JSON below:
https://console-openshift-console.apps.odh-cl1.apps.os-climate.org/k8s/ns/sandbox/pods/physrisk-api2-42-vjmtd/logs

{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "the server has asked for the client to provide credentials ( pods/log physrisk-api2-42-vjmtd)",
  "reason": "Unauthorized",
  "details": {
    "name": "physrisk-api2-42-vjmtd",
    "kind": "pods/log"
  },
  "code": 401
}

**Comment by joemoorhouse** [comment]
Hi @MichaelTiemannOSC, @redmikhail,
would you know who I can ask to help with this?

FYI @mvarfima 

Thanks,
Joe

**Comment by HeatherAck** [comment]
Also added @ModeSevenIndustrialSolutions

**Comment by redmikhail** [comment]
@joemoorhouse One of the Openshift nodes due to the issue with underlying AWS EC2 instance was only partially available. While pods on this node have continue to run access to logs was not working . It was corrected and logs should be available. Please validate and let me know if issue still exist

**Comment by joemoorhouse** [comment]
Thanks for that Mikhail. Indeed fixed the issue!
