### ISSUE TITLE
set rights to new biodiversity repository for sostrades-transition-risk

### ISSUE THREAD

**Issue by sostrades-pjbarjhoux** [os-climate/os_c_data_commons#369]
Hi,

Would it be possible to grant  admin rights on [https://github.com/os-climate/biodiversity](https://github.com/os-climate/biodiversity) to the group **sostrades-transition-risk** please?

Thanks

**Comment by sostrades-pjbarjhoux** [comment]
@sostrades-dpeltre @cap-dpeltre

**Comment by cap-dpeltre** [comment]
Hello, can an admin from the os-climate group help us ?

**Comment by MichaelTiemannOSC** [comment]
Sorry I didn't see this the first time.  I've added Maintain privs to sostrades-transition-risk.  Please re-open if it doesn't work for you.
