### ISSUE TITLE
readthedoc access request

### ISSUE THREAD

**Issue by sostrades-pjbarjhoux** [os-climate/os_c_data_commons#370]
Hi,

We are building a documentation for SoSTrades platform and WITNESS, and would like to plublish it through the [readthedoc](https://about.readthedocs.com/). Thanks to a webhook, readthedoc will deploy the documentation on a dedicated website each time a change in the concerned repositories will be detected.

To that purpose, we need osclimate to grant access to the repositories : 
![MicrosoftTeams-image (1)](https://github.com/os-climate/os_c_data_commons/assets/97045220/525172ef-33a7-45eb-a5b8-e8a28ce6a723)

Could you please grant access to readthedocc app, please?

Thanks

**Comment by MichaelTiemannOSC** [comment]
I granted the access request.

**Comment by sostrades-pjbarjhoux** [comment]
many thanks Maichael!
