### ISSUE TITLE
Add members to organization and sostrades-transition-risk team

### ISSUE THREAD

**Issue by ggoyon** [os-climate/os_c_data_commons#375]
Hi,

Could you please invite these github accounts to os-climate organization and add them to sostrades-transition-risk team ?
Team link : https://github.com/orgs/os-climate/teams/sostrades-transition-risk

Accounts :
[b4pm-devops](https://github.com/b4pm-devops)
[clabarth](https://github.com/clabarth)
[naiksushrita](https://github.com/naiksushrita)
[simaosr](https://github.com/simaosr)

Thank you very much !

**Comment by MichaelTiemannOSC** [comment]
Done.

To answer the question: the permission to add members to the organization belongs only to organizational owners.  Once people are members and are doing repo-level stuff, then maintainers of that repo can grant those permissions.

Copying @ModeSevenIndustrialSolutions for suggestions as to a better way to channel org membership requests so that our centralized services (Matt, myself, perhaps a few others) can be auto-assigned these requests rather than relying on seeing them originate from within each repo.

**Comment by ggoyon** [comment]
Thank you very much !

From what I understand, we have to make issues here to ask to add / remove people and teams on the organization.
Then I already have rights to add / remove people in teams and repositories when they are in the organization.

Also to make managing the repositories easier, I would like to have 2 subteams created (so I can then provide specific rights to the teams for each repo).

Could you please create the following subteams of [sostrades-transition-risk](https://github.com/orgs/os-climate/teams/sostrades-transition-risk/teams) and put me as Maintainer on them, so I can then manage members of these ?
sostrades-transition-risk - Repository admins
sostrades-transition-risk - Devops


We have a new joiner, could you please add him to os-climate ?
[vdr0u3t](https://github.com/vdr0u3t)

For information we have 4 members that left the project the last months, you can remove them from the organization if you want :
[fadwaouniss](https://github.com/fadwaouniss)
[KAJBORKA](https://github.com/KAJBORKA)
[sushilkumarmane](https://github.com/sushilkumarmane)
[eloquet](https://github.com/eloquet)

**Comment by MichaelTiemannOSC** [comment]
Some poor indenting above...Matt has actually done all of the above, not merely repeated the ask...

**Comment by ModeSevenIndustrialSolutions** [comment]
Indeed, the GitHub interface slightly mangled my update; apologies for any confusion!

**Comment by ggoyon** [comment]
Thank you very much, closing the issue as resolved :)
