### ISSUE TITLE
OSC-Platform-018: Data Commons Browser support

### ISSUE THREAD

**Issue by MichaelTiemannOSC** [os-climate/os_c_data_commons#38]
A data commons browser is really nothing more than a grid tool that has appropriate columns and filtering mechanisms to show users what rows of data/data sets that match their selection criteria are available in the data commons.  datasette provides an excellent grid-style interface to web browsers, permitting faceted browsing, geospatial browsing (with integrated clusermaps), and easily accessible interfaces to SQL queries (ranging from just defining a particular range or match to full-blown sql queries).

However, to make the browser meaningful to users of the Data Commons, there must be a common framework and metadata for defining datasets and their contents so that a simple browser can simply do its job.

In the User Journey document (slides 12-15, see https://github.com/os-c/PlatformUI/blob/main/docs/OS-Climate%20Platform%20UI%20%20--%20guidance%20and%20user%20journey.pptx) the following is clearly assumed:
- a user can search through Sectors and Industries(1), within a time period(2), narrowed by a Regional, or Country-based starting point(3), to identify Companies for which some data is available.  (The search hierarchy order is arbitrary)
- users will be able to select one or more companies that match the selected criteria for further browsing
- once we know company(4) and timeframe, the browser will show a list of reported metrics (date-based observations) and how those metrics are classified according to an ESG framework (OSC Factors, SASB, WRI, TCFD, etc).  Users can sort based on company attribute(s), date, factor, quantity, etc.

The purpose of this issue is to highlight up front that any data we enter into the data commons that is tied to a corporate entity needs to have proper browser metadata so that the browser can do its (simple) job.  Thomas Kirchherr (initial assignee) understands this problem well, but will likely delegate it to the right person to shepherd its technical implementation.

At a later date, we may wish to generalize the browser so that it is useful not only to those exploring corporate data availability, but those interested in solving general data management problems.

(1) There are many Sector/Industry classification systems: ISIC, SIC, BIC, NACE, SASB, etc.  We may support more than one, but must support at least one.  
(2) Time period requires a data selector (that allows unbounded "before" or "after" dates)  
(3) There are many definitions of Regions and Countries.  We may support more than one, but must support at least one.  
(4) Companies have several associated attributes, including trade name, legal domicile, ISIN, industry classification categories and codes, etc.

**Comment by MichaelTiemannOSC** [comment]
Related: https://github.com/os-climate/os_c_data_commons/issues/48

**Comment by erikerlandson** [comment]
@oindrillac @aakankshaduggal  were two recommendations from @MichaelClifford  for SuperSet expertise

**Comment by MichaelTiemannOSC** [comment]
@oindrillac @aakankshaduggal Please let me know when I can share my screen and show you want simple things I'm doing with Datasette that might be done in SuperSet instead.  Thanks!

**Comment by oindrillac** [comment]
hello @MichaelTiemannOSC! sure, I set some time for us to sync up tomorrow on google calendar. Please feel free to move it around if there is a better time slot :)

**Comment by caldeirav** [comment]
Now we have OpenMetadata up and running with Superset dashboard integration, we can start working on an integrated dashboard for this requirement.

**Comment by HumairAK** [comment]
@caldeirav they just need to log in. That will create the user, then you should be able to add them to the team.

**Comment by eoriorda** [comment]
Action : Need some enhancements from the openmetadata group. 
Catalog is there in Openmetadata. CAn we ingest a dashboard. 
Collection of Browsers build on superset and available on the dashboard.
Depedency - Openmeta data upgrade.

**Comment by caldeirav** [comment]
Dependent on OpenMetadata upgrade to v0.12.0 as per issue #202

**Comment by HeatherAck** [comment]
OpenMetaData is done.  Need developer support to build UI for browser creation, plus taxonomy defined. @ericbroda - do you have any base requirements to help team get started

**Comment by HeatherAck** [comment]
Team agrees to use Open MetaData as the browser. Need taxonomy to provide system of organization (next step:  create new set of issues with U-Reg) - requires sufficiency of data (e.g. carbon, corp data, corp hierarchy data, etc).  Datasette to be considered as pre-ingestion step for complex, large datasets.
