### ISSUE TITLE
OSC-Platform-020: Download rest of ESG documents from S&P Global

### ISSUE THREAD

**Issue by caldeirav** [os-climate/os_c_data_commons#40]
There are around 32000 documents to be downloaded in addition to the existing 8500. For now we shall only do a SFTP from the existing S&P Global repository:

URL: sftp://edx.spglobal.com/Products/ESGFilings
Port: 22
ESGD5020
027p3Y+0$

Likely this will need to be automated with a daily process in the future. Note: Dependency on S&P adding the remaining documents in the SFTP folder.

**Comment by HeatherAck** [comment]
new count is 75K (we will receive updated versions of the original ~8500).  Related LF Jira:  https://jira.linuxfoundation.org/plugins/servlet/theme/portal/2/IT-24329

**Comment by HeatherAck** [comment]
Updated info for S&P Global docs:

URL: sftp://edx.spglobal.com/Products/ESGFilings

Port: 22

ESGD5020

27wr0N$,i

**Comment by HeatherAck** [comment]
the ~75K reports are now available
Here is the credential which you can use to access the documents from sftp path, attaching along here excel file that contains the document definition. I placed all the files in one folder as multiple folder creation was not allowing under same account, so you can get all the docs from one folder.

 

HostURL: sftp://edx.spglobal.com/Products/ /Products/OSC-ESG

UserName: ESGD5020

Password: 27wr0N$,i

Port: 22

**Comment by HeatherAck** [comment]
@redmikhail will investigate and see where best to put in S3 bucket.  what is lifecycle process for these files?
- ingest from S&P bucket [write a notebook to call osc-ingest tools]
- load into pachyderm and version it [@caldeirav are we using pachyderm or DVC?]
- load into iceberg tables on CL2
@HeatherAck to follow up with @JeremyGohBNP to determine ingestion pipeline process.

**Comment by eoriorda** [comment]
Eric can do this download  using lfdp which can set remotes for download and upload. Running locally on Erics machine.  LFTP has a smart funtcion which moves new and changed . Can move this to a container .
Mikhail would like to see this in a repeatable fashion , move it to AWS as a virtual machine or container.  
Like to have it spawned and run on a shared instance.
Eric is working on getting this in a reproducable and predictable manner for Azure . Take what he has done and apply to AWS but need to know what folder to put it in.

**Comment by eoriorda** [comment]
Working for Azure - 
Eric needs to find a way to automate it.  Need a way to containerize this .   Eric needs to know the folder in AWS .   @redmikhail to provide the folder location

**Comment by redmikhail** [comment]
@eoriorda It should go to s3://redhat-osc-physical-landing-647521352890/SPGI_ESG_Filings/ together with the initial drop of ESG documents unless I am misreading what it is for

**Comment by HeatherAck** [comment]
eric b. pending credentials from @redmikhail - will move files; test automation using GitHub actions (sync operation, copy over new files, job to run at X interval - containerized but manually triggered)

**Comment by HeatherAck** [comment]
@MightyNerdEric can you please let us know if this is complete?

**Comment by HeatherAck** [comment]
@rynofinn to work with @MightyNerdEric to resolve credential issues

**Comment by MightyNerdEric** [comment]
Current status: 16.7k files have been transferred of 78k. The first week of this transfer has been very inefficient, but it's now settled into a constant pace. At the current transfer rate, it will take another week to complete. 

However, now that I full access to the AWS account, I can properly setup a direct transfer (rather than using my own computer as a midpoint), so that will hopefully increase the throughput. But I can't guarantee that; given how little of my own total bandwidth is being used, it's entirely possible that we're already seeing the maximum transfer rate.

**Comment by HeatherAck** [comment]
70870 as of 3-Oct.
