### ISSUE TITLE
gpu enabled node(s) not advertising `nvidia.com/gpu` resource

### ISSUE THREAD

**Issue by erikerlandson** [os-climate/os_c_data_commons#45]
According to the cluster machine-set, we should have one node that is gpu-enabled, but none of the nodes show the standard `nvidia.com/gpu` resource to allow scheduling based on gpu resource

```sh
[eje@localhost ~]$ oc get node -o jsonpath="{range .items[*]}{..allocatable}{'\n'}{end}"

map[attachable-volumes-aws-ebs:25 cpu:7500m ephemeral-storage:114396791822 hugepages-1Gi:0 hugepages-2Mi:0 memory:30954864Ki pods:250]
map[attachable-volumes-aws-ebs:25 cpu:7500m ephemeral-storage:114396791822 hugepages-1Gi:0 hugepages-2Mi:0 memory:30954864Ki pods:250]
map[attachable-volumes-aws-ebs:25 cpu:15500m ephemeral-storage:114396791822 hugepages-1Gi:0 hugepages-2Mi:0 memory:30953132Ki pods:250]
map[attachable-volumes-aws-ebs:25 cpu:3500m ephemeral-storage:114396791822 hugepages-1Gi:0 hugepages-2Mi:0 memory:14784740Ki pods:250]
map[attachable-volumes-aws-ebs:39 cpu:3500m ephemeral-storage:114396791822 hugepages-1Gi:0 hugepages-2Mi:0 memory:61706180Ki pods:250]
map[attachable-volumes-aws-ebs:25 cpu:7500m ephemeral-storage:114396791822 hugepages-1Gi:0 hugepages-2Mi:0 memory:30954864Ki pods:250]
map[attachable-volumes-aws-ebs:25 cpu:3500m ephemeral-storage:114396791822 hugepages-1Gi:0 hugepages-2Mi:0 memory:14784740Ki pods:250]
map[attachable-volumes-aws-ebs:25 cpu:7500m ephemeral-storage:114396791822 hugepages-1Gi:0 hugepages-2Mi:0 memory:31298928Ki pods:250]
map[attachable-volumes-aws-ebs:25 cpu:7500m ephemeral-storage:114396791822 hugepages-1Gi:0 hugepages-2Mi:0 memory:30954864Ki pods:250]
map[attachable-volumes-aws-ebs:25 cpu:3500m ephemeral-storage:114396791822 hugepages-1Gi:0 hugepages-2Mi:0 memory:14784740Ki pods:250]
```

**Comment by MichaelTiemannOSC** [comment]
Can we please get this resolved (i.e., make a plan to have the cluster use the GPUs that are preferred in the zone that we are using)?

@dvizzini107

**Comment by redmikhail** [comment]
@MichaelTiemannOSC we have currently at least 3 nodes with enabled GPU's (older models) , we will increase this number to 4 . Plan is to see if we can use current GPU enabled nodes (p2 instances) for the tasks related to  COP26 presentation.  I believe that we were able to successfully deploy test notebook that uses gpu , next step is to adapt the actual pipeline to use these nodes  (@erikerlandson  correct me if I am wrong) .  Considering that to move to different availability zone we need to provision new OCP cluster it makes sense to do this transition post COP26 (to avoid disruptions and have solidified platform and configuration ) . I think that this issue can be closed at this point and track remaining tasks in separate tickets

**Comment by erikerlandson** [comment]
This is fixed, and we have verified jupyter notebook can access the gpus
