### ISSUE TITLE
OSC-Platform-027: Integration of schema / column metadata with visualization

### ISSUE THREAD

**Issue by caldeirav** [os-climate/os_c_data_commons#51]
As a data scientist / developer, I want to be able to plug schema / column information into the front-end when building data visualisation.

An example use-case would be to have metadata about unit of measure for emissions captured in schema / column metadata, and make this accessible in a front-end such as Superset.

**Comment by caldeirav** [comment]
Blocked due to issue #107 - unable to build linked query between data set and associated metadata. @HumairAK

**Comment by eoriorda** [comment]
This is dependent on a feature enhancement with Open Metadata  
 https://github.com/open-metadata/OpenMetadata/issues/5492 which would build meta data from a Trino instance .  
Workaround is still being tested . Vincent will open an issue for this .

**Comment by caldeirav** [comment]
I have managed to workaround the Trino metadata ingestion limitation (in the connector) by using Trino ingestion for loading but going through DBT for transformation and metadata ingestion. 

Example in https://github.com/os-climate/wri-gppd-ingestion-pipeline will be documented as a result. 

@MichaelTiemann the idea is users will be able to perform data discovery (including data sample) through OpenMetadata catalogue and from there they can get a SQL query to be used in a dashboard such as Superset. We can also have example dashboards with cross-queries available in OpenMetadata itself.
