### ISSUE TITLE
onboard `redhat-osc-physical-landing` S3 bucket

### ISSUE THREAD

**Issue by erikerlandson** [os-climate/os_c_data_commons#52]
We need to get `redhat-osc-physical-landing` s3 bucket attached to trino

- [x] configure a new hive catalog for that bucket
- [x] stand up a new metadata server pod for that catalog
- [ ] verify we can create a simple table on the bucket and see it from trino

**Comment by erikerlandson** [comment]
@HumairAK  the catalog name `osc-physical-landing` is causing trino problems, because there are dashes in the name, can you rename this with underscores: `osc_physical_landing`

```python
cur.execute('show catalogs')
cur.fetchall()

[['default'], ['demo1'], ['jmx'], ['osc-physical-landing'], ['system']]
```

**Comment by MichaelTiemannOSC** [comment]
This issue is subsumed by https://github.com/os-climate/os_c_data_commons/issues/68
