### ISSUE TITLE
add Mike Clifford to os-climate openshift cluster

### ISSUE THREAD

**Issue by erikerlandson** [os-climate/os_c_data_commons#53]
tasks

- [x] invite Mike to os-climate github org, and specifically odh-env-users
- [x] do openshift side configs
- [x] verify Mike can log into cluster, etc

**Comment by MichaelClifford** [comment]
:+1:  Any additional info needed from me to get added to the cluster @HumairAK

**Comment by erikerlandson** [comment]
cc @HumairAK

**Comment by HumairAK** [comment]
on it

**Comment by HumairAK** [comment]
can you guys outline what sort of access is needed?

**Comment by erikerlandson** [comment]
They need to run ODH: jupyter, trino, superset, etc.  I don't think they need cluster admin, but that is OK too if necessary.

**Comment by HumairAK** [comment]
I think we ought to limit cluster admin if we can help it. Cluster resources should for the most part only go through git.

**Comment by erikerlandson** [comment]
IIUC Mike has access, closing.
