### ISSUE TITLE
create "official" trino user names with more secure passwds

### ISSUE THREAD

**Issue by erikerlandson** [os-climate/os_c_data_commons#55]
Recommend leaving the current names for now, the ones Humair created earlier, but we should start creating some more official names.  I am thinking like:

`erik_erlandson`
`humair_kahn`
`vincent_caldeira`
`michael_tiemann`
`etc`

Maybe also a couple of actual demo usernames, `demo_user_a`, `demo_user_b`, maybe just give these read/write access to `demo1` catalog data, and read-only access to `default` and `system` catalog.

And giving these better (random) passwords. The first 10 characters of uuid or something.

We will need to create some usernames and passwords for people we on-board, ideally at least people attending training next friday.   cc @caldeirav @MichaelTiemannOSC

**Comment by erikerlandson** [comment]
cc @HumairAK 

initial users and user groups:
- [ ] BNPP NLP: Jeremy Goh, Lea Deleris, Andra Anoaica
- [ ] BNPP Entity Matching: Ludan Stoeckle, Rui Dias Morais, Patrycia Barros
- [ ] Allianz (Many Workstreams, Leyla Javadova): David Winkel, Christian Meyndt, Ismail Demir, Tu Schmucker, Oleksandr Anufriyev
- [ ] Ortec Finance: Bert Kramer, Joris Cramwinckel
- [ ] EY: Mike Zehetmayr
- [ ] OS-Climate: Michael Tiemann, Mike Platt

We should define trino user groups for the above,  by parent company/org:
- [ ] bnpp
- [ ] allianz
- [ ] ortec
- [ ] ey
- [ ] osclimate

For now, all groups have `read` access to all current catalogs, schemas, tables. If and when there is a need for per-group access, we can work that out on a case by case basis.

All groups have write/create access to `demo1`

**Comment by caldeirav** [comment]
The Trino setup should be based on GitHub user groups and not by parent company, as per our data security architecture: https://docs.google.com/presentation/d/1eL2XKeBafPK8ZqhpKrqBiwygTcb--TsTouyz5Y7xjg8/edit#slide=id.gef587ef828_0_0

High level summary of requirements based on my thinking so far (to be validated with the dev team as we go along):
- We should have one Trino catalog per repository doing ingestion or processing e.g. itr_data_pipeline catalog
- Within the catalog, data sources would have their own schema in this catalog e.g. urgentem and lseg schema under itr_data_pipeline catalog. Also the streams will create their own schemas for processed data e.g. emissions based on urgentem + lseg + some corporate data
- Default access to be given would be W at the catalog level for the entire GitHub team that has access to the repository i.e. os-climate-itr-tool-project-team has R access to itr_data_pipeline catalog
- Access in RW mode at catalog level would be given to admin and developer sub-teams e.g. itr-data-pipeline-admin, itr-data-pipeline-developers in this case

When giving access to the outpuy of itr_data_pipeline, the idea would be to have a schema for this, and give schema level read access only to another team.

**Comment by HumairAK** [comment]
Hi, it's not clear to me which github orgs map to which users in the above list, can I get an explicit mapping in the form of: 

```
<trino_group_name_1>:<user_1>,<user_2>
<trino_group_name_2>:<user_1>,<user_2>

...
```

**Comment by erikerlandson** [comment]
@HumairAK  I have a proposal:  instead of using "firstname_lastname" let's define trino accounts that are the same as github account names. 

This will have advantages:
- it makes it easy to define mappings. github_team->user_group and github_user->trino_user.
- the membership relationships are the same, and so can be derived directly from the github-org (and so also are easy to explain)
- it is easy to remember your trino user name, it is just your github account
- at whatever point we get true o-auth, the names remain the same

I will try to get specific names, but for now can you do users and groups corresponding to these github teams:
- `aicoe-osc-demo`
- `os-climate-corporate-data-project-team`
- `os-climate-itr-tool-project-team`

If those are too long, can use `corporate_data_project` and `itr_tool_project`

for ref, see:
https://github.com/orgs/os-climate/teams

**Comment by HumairAK** [comment]
@erikerlandson can I get starter members for `os-climate-corporate-data-project-team` and `os-climate-itr-tool-project-team`

**Comment by erikerlandson** [comment]
for xref:  https://github.com/operate-first/apps/pull/1010
