### ISSUE TITLE
request trino account

### ISSUE THREAD

**Issue by MichaelTiemannOSC** [os-climate/os_c_data_commons#60]
I am attempting to see whether following the steps documented at os-climate-diagram.pdf (page 2) leads me to a notebook that can access the WRI data I uploaded to the demo3 bucket.

**Comment by erikerlandson** [comment]
@MichaelTiemannOSC  we are currently managing access levels by trino user-groups that correspond to os-climate github teams, per the data governance docs (cc @caldeirav):
 https://github.com/orgs/os-climate/teams

Is there a team that corresponds to your access needs or should we create a new one, or do you need admin access?

**Comment by MichaelTiemannOSC** [comment]
I am a member of the odh-evn-users team, which I think should be sufficient.  But if I need a more specific permission, this would be the demo-3 user group (I think).

Michael

**Comment by erikerlandson** [comment]
`odh-env-users` is a "special" group for allowing openshift cluster access - it does not correspond to a trino access group.

@HumairAK Recommend we create a trino user-group corresponding to the `os-climate-data-commons-project-team`, and add Michael Tiemann and ourselves to that, and give it appropriate read access, write access to demo1

**Comment by erikerlandson** [comment]
Verified trino connection is successful
