### ISSUE TITLE
add gpu enabled node to osc openshift cluster

### ISSUE THREAD

**Issue by erikerlandson** [os-climate/os_c_data_commons#61]
We currently have one gpu-enabled node. Now that we are ready to begin supporting os-climate members using gpus, we will need to start adding more gpus.  I recommend running 4 gpu enabled nodes.
cc @caldeirav

**Comment by erikerlandson** [comment]
cc @MichaelTiemannOSC  -  regarding approval for AWS resource usage

**Comment by redmikhail** [comment]
@erikerlandson we have had some unused quota and I have added two nodes with GPU . I will request increase as well

**Comment by MichaelTiemannOSC** [comment]
It appears that 4 GPUs are a valid option for notebooks.  Closing as this appears completed.
