### ISSUE TITLE
create catalog for `dev-osc-physical-landing-309737258120`

### ISSUE THREAD

**Issue by erikerlandson** [os-climate/os_c_data_commons#62]
We need to expose a trino catalog for a bucket 
`dev-osc-physical-landing-309737258120`

cc @caldeirav

**Comment by HumairAK** [comment]
the wording is a bit confusing for me, do you mean, add an new trino catalog for this new bucket?

**Comment by erikerlandson** [comment]
@HumairAK  yes

**Comment by MichaelTiemannOSC** [comment]
I will note in passing that this bucket is a bit of a dumping ground, and is not organized as a best-practices data source.  We should not knock ourselves out trying to get this catalog "right"; rather just make the data reasonably accessible.

**Comment by HumairAK** [comment]
any suggestions on the name for this catalog? see [here](https://github.com/operate-first/apps/tree/master/kfdefs/overlays/osc/osc-cl1/trino/hive-metastores) for current catalogs (dir names in that link)

**Comment by redmikhail** [comment]
I have commented on this issue in https://github.com/os-climate/os_c_data_commons/issues/66 . Ultimately we need to figure out if we still want to use buckets across two AWS accounts `309737258120` and `647521352890` where second one is where OCP cluster with our ODH is running or try to use account `647521352890` for everything. If we still need to keep data in two accounts we have options : a) syncing data across buckets -https://aws.amazon.com/blogs/storage/how-to-use-aws-datasync-to-migrate-data-between-amazon-s3-buckets/ b) grant cross-account access - https://aws.amazon.com/premiumsupport/knowledge-center/cross-account-access-s3/ o

**Comment by erikerlandson** [comment]
for name, recommend `osc_physical_landing_dev`

For buckets that are explicitly used by our trino deployment for catalogs, I believe it would ultimately be simplest to create these all from the same account, however would like input from @caldeirav and @MichaelTiemannOSC  on this topic.

There will also be buckets that other community members supply for other data, that will be from other accounts, but access via the python s3 connection for these should be simpler, and primarily read-only from the point of view of the data commons platform.

**Comment by redmikhail** [comment]
Thank you @MichaelTiemannOSC  it makes sense, I guess for now we need to sync data from the pudl folder in *120 to our account , is it something that you can do or we can ask AWS to help us with that ? @erikerlandson we have redhat-osc-physical-landing-647521352890 s3 bucket for all incoming data which also backed by sftp access sftp.landing.apps.os-climate.org (if anyone doesn't want/can't use S3 protocol) and already has catalog created , I wonder if want to just re-use the same bucket?

**Comment by erikerlandson** [comment]
The primary access control granularity will be `schema`, and so from that point of view a single bucket can contain an arbitrary number of schemas.

There may be a use case for a "dev" bucket and a "production" bucket so that ingest pipelines do not have to share access credentials between dev and prod.

**Comment by HumairAK** [comment]
okay -- just looking to clarify, is this issue blocked on user creds for said bucket?

**Comment by MichaelTiemannOSC** [comment]
I have reached out to Madhu Bussa for instruction on how to give this specially created user access via permission sets/roles we have created.  In the mean time, I stand ready to copy whatever other data needs to be copied from the *120 account to the *890 account.  The data in the *120 account is not updated by anybody so there's no fear of data forking.

**Comment by erikerlandson** [comment]
There will no longer be any trino catalog for the physical landing bucket, so I am closing this.
