### ISSUE TITLE
conda support HOWTO documentation/configuration support needed

### ISSUE THREAD

**Issue by MichaelTiemannOSC** [os-climate/os_c_data_commons#64]
As a data scientist, I want to use conda to install interesting packages.  There is no conda support in either the minimal or data science JupyterLab notebooks for the odh-env-user using Python 3.8.  When I install miniconda3 using the standard Linux install script, it places the miniconda3 environment in /opt/app-root/src, with two unhelpful consequences:

1. This puts pressure on the small default amount of space allocated to the Jupyter notebook.  Conda installs rapidly use up hundreds of MB to GB of space
2. Despite starting the notebook with SHELL=/bin/bash, conda init claims no action was taken after initializing bash, conda activate doesn't recognize conda init as having been run, and the conda command cannot be found in the default path (which should be a consequence of running conda init).

As a result there is no easy way to run !conda commands from within the JupyterLab environment.

**Comment by MichaelTiemannOSC** [comment]
I've made some progress by issuing this command from an active conda environment in my terminal window:

`conda install nb_conda_kernels`

This causes the 'base' environment to show up as a kernel option, which enables the conda commands to be used.  Is this the correct solution?

**Comment by goern** [comment]
@pacospace @harshad16 FYI

**Comment by MichaelTiemannOSC** [comment]
The cause of the "Server Error 500" is:

`PermissionError: [Errno 1] Operation not permitted: '/opt/app-root/share/jupyter/lab/staging/index.js'`

The file's permissions and its enclosing directory are are 775 for root/builder/other.

**Comment by MichaelTiemannOSC** [comment]
I've attempted to address the JupyterLab part of the problem in a more public forum, here:  https://github.com/jupyter-on-openshift/jupyter-notebooks/issues/35

@goern @pacospace @harshad16

**Comment by goern** [comment]
Hey @MichaelTiemannOSC thanks for trying conda out on the ODH environment, I wonder why you need conda at all? is there something that you cant do using pip/pipenv/micropipenv? is there any package provided by conda that are not available from upstream?!

**Comment by MichaelTiemannOSC** [comment]
My purpose in using Conda was the promise that it did under-the-hood adjustments to Jupyter environment to take care of extensions needed by various packages (such as plotly and/or ipyleaflet).  My understanding was that pip is great for slamming packages into libraries, but then it leaves to the user the manual task of installing/loading extensions, which I know is fraught with difficulties.  Conda could be completely redundant with how ODH services notebooks, and I'd be happy to learn how to provision notebooks within my ODH environment from the platform side.  I just don't know where to start (since I'm "just a user" in my current story).

**Comment by MichaelTiemannOSC** [comment]
> Hey @MichaelTiemannOSC thanks for trying conda out on the ODH environment, I wonder why you need conda at all? is there something that you cant do using pip/pipenv/micropipenv? is there any package provided by conda that are not available from upstream?!

So after discovering that the elyra notebook starting point solves my real problems, this is open only because the permissions problem for index.js will continue to thwart the next person who decides they need conda in a Minimal notebook environment.

**Comment by goern** [comment]
+1 thanks for that!!

**Comment by MichaelTiemannOSC** [comment]
This is all sorted now.
