### ISSUE TITLE
add some additional launcher options for increased mem but same CPU

### ISSUE THREAD

**Issue by erikerlandson** [os-climate/os_c_data_commons#65]
We have a use case for notebook environment that uses more memory without requiring additional cpus. This can be done by adding the appropriate singleuser profile.

**Comment by erikerlandson** [comment]
cc @MichaelTiemannOSC

**Comment by MichaelTiemannOSC** [comment]
Suggest 1 CPU with 8 GB Filesystem / 8 GB RAM for prototyping.  User profile could be called "Small Geospatial".

**Comment by erikerlandson** [comment]
cc @HumairAK   I need to figure out where the PVC sizes are configured in the overlays, and/or if those can now be configured via singleuser profiles (that did not used to be the case)

**Comment by erikerlandson** [comment]
Resolved, there are three new size options:
- `1 cpu, 2GB mem`
- `1 cpu, 4GB mem`
- `1 cpu, 8GB mem`

Additionally, the default user PVC is increased to 16GB
