### ISSUE TITLE
user can access s3 bucket but trino is erroring out

### ISSUE THREAD

**Issue by erikerlandson** [os-climate/os_c_data_commons#66]
@caldeirav  has a situation where he can access the s3 bucket but when he tries to create trino database table, trino is erroring out.

**Comment by erikerlandson** [comment]
The reproducer is essentially, "run this notebook"
https://github.com/os-climate/data-platform-demo/blob/master/notebooks/pudl_ingestion_sample.ipynb

The failure is in the last cell, where it tells trino to expose the uploaded file as a table.  So the s3 access is working for uploading the files but trino's attempt to access the same bucket is failing.

**Comment by redmikhail** [comment]
S3 bucket `s3a://dev-osc-physical-landing-309737258120` is in different AWS account `309737258120` from where OCP cluster is running  ( `647521352890` ) . If want to use it , we need someone who has access to  `309737258120`  to provide access across accounts https://aws.amazon.com/premiumsupport/knowledge-center/cross-account-access-s3/  or alternatively sync and use s3 bucket that we already have - `redhat-osc-physical-landing-647521352890`

**Comment by erikerlandson** [comment]
This is resolved, closing.
