### ISSUE TITLE
support plotly in the odh elyra jupyter environment

### ISSUE THREAD

**Issue by erikerlandson** [os-climate/os_c_data_commons#67]
We have a use case for building plotly-based interfaces in jupyter notebooks.  @MichaelTiemannOSC was able to hack something that worked, but it involved breaking out in to the "raw" jupyter interface and creating a conda environment.  The proper solution would be building elyra notebook image with plotly support, possibly based on Michael's example.

**Comment by MichaelTiemannOSC** [comment]
I'll give elyra a whirl and let you know.  Do you want me to check in any elyra-related notebooks here, or in some other repo?

**Comment by erikerlandson** [comment]
I propose that we maintain a "elyra with plotly extensions" image build here:
https://github.com/os-climate/elyra-plotly-notebook

**Comment by MichaelTiemannOSC** [comment]
I am happy to report success, after a fashion.

1.  Created Elyra notebook image with Medium parameters and SHELL=/bin/bash
2.  Ran these commends in a shell:

```
#!/bin/bash

pip3 install ipywidgets plotly

# For Plotly version 4, deal with plotlywidget extension (which is automatic in Plotly 5 and JupyterLab)
# jupyter nbextension install plotlywidget --user --py
# jupyter nbextension enable plotlywidget --user --py

# Establish basic geo libraries for Physical Risk
pip3 install pandas geopandas matplotlib affine snuggs ipyleaflet

# If not running JupyterLab, activate the ipyleaflet extensions where we can see them
# Check Edit->nbextensions config menu item to see that ipyleaflet extension is visible
# /opt/app-root/miniconda3/bin/jupyter nbextension install ipyleaflet --user --py
# /opt/app-root/miniconda3/bin/jupyter nbextension enable ipyleaflet --user --py

# Install known-good rasterio from PyPi
pip3 install rasterio
```
I checked the status of the JupyterLab extensions, and all reported OK:

```
[1000640000@jupyterhub-nb-michaeltiemannosc ~]$ jupyter labextension list
JupyterLab v3.0.14
/opt/app-root/share/jupyter/labextensions
        jupyterlab_requirements v0.6.4 enabled OK (python, jupyterlab-requirements)
        nbdime-jupyterlab v2.1.0 enabled OK
        jupyter-leaflet v0.14.0 enabled OK
        jupyterlab-plotly v5.3.1 enabled OK
        @jupyterlab/git v0.30.0 enabled OK (python, jupyterlab-git)
        @jupyter-widgets/jupyterlab-manager v3.0.1 enabled OK (python, jupyterlab_widgets)
        @jupyter-server/resource-usage v0.5.0 enabled OK (python, jupyter-resource-usage)
        @krassowski/jupyterlab-lsp v3.6.0 enabled OK (python, jupyterlab-lsp)

Other labextensions (built into JupyterLab)
   app dir: /opt/app-root/share/jupyter/lab
        @elyra/code-snippet-extension v2.2.4 enabled OK
        @elyra/metadata-extension v2.2.4 enabled OK
        @elyra/pipeline-editor-extension v2.2.4 enabled OK
        @elyra/python-editor-extension v2.2.4 enabled OK
        @elyra/r-editor-extension v2.2.4 enabled OK
        @elyra/theme-extension v2.2.4 enabled OK


Disabled extensions:
    @jupyterlab/launcher-extension (all plugins)
```

So I launched a very simple notebook script:

```
import plotly.graph_objects as go
from ipywidgets import widgets

# from ipywidgets import interactive

reset_button = widgets.Button(
    description='Reset', disabled=False,
    button_style='', # 'success', 'info', 'warning', 'danger' or ''
    tooltip='Reset Parameters',
    icon='arrow-rotate-left' # (FontAwesome names without the `fa-` prefix)
)
reset_button
```

This resulted in failure with the Reset button rendering as the textual representation of the widget.  Then, Step 3:

3.  Refresh JupyterLab page, which causes JupyterLab to rebuild.  When I then restarted the kernel, the Reset button rendered as it should.

SUCCESS!

I'm very happy to have a modern JupyterLab environment that works with both my ITR prototype and Nikos Dimakis's Physical Risk prototype.  It is clean, snappy, and inspires confidence.

**Comment by erikerlandson** [comment]
@MichaelTiemannOSC  so to clarify, are you finding that the existing ODH elyra image has the plotly support you need?

Tangentially, you can execute `pip install` commands in a notebook cell, you don't need the shell to do that.

**Comment by MichaelTiemannOSC** [comment]
What the existing ODH elyra image has is the necessary ability to rebuild JupyterLab after installing the necessary plotly support.  The next step would be for me to translate the installation instructions given in the shell script into a YAML file that pre-loads the necessary libraries for a true elyra-plotly notebook.  The first step was to show how we could go from the initial elyra-vanilla notebook to one supporting plotly.

**Comment by erikerlandson** [comment]
ack, we can use the `elyra-plotly-notebook` repo above to pre-install requirements

**Comment by MichaelTiemannOSC** [comment]
I added a requirements.txt file with snapshots of the important files.  Many others will load in to satisfy dependencies.

**Comment by MichaelTiemannOSC** [comment]
This is for all intents and purposes working for me now.
