### ISSUE TITLE
Data type error when ingesting PUDL data intro Trino

### ISSUE THREAD

**Issue by caldeirav** [os-climate/os_c_data_commons#72]
Revised demo sample committed at https://github.com/os-climate/data-platform-demo/blob/master/notebooks/pudl_ingestion_sample.ipynb

I have an issue with the data structure (suspect the schema mapping) as when I try to read the ingested data i get the following: TrinoQueryError: TrinoQueryError(type=INTERNAL_ERROR, name=GENERIC_INTERNAL_ERROR, message="io.trino.spi.type.DoubleType", query_id=20210930_072151_00086_iz7p7)

**Comment by erikerlandson** [comment]
```python
_p2smap = {
    'string': 'varchar',
    'float32': 'real',
    'Float32': 'real',
    'float64': 'double',
    'Float64': 'double',
    'int32': 'integer',
    'Int32': 'integer',
    'int64': 'bigint'
    'Int64': 'bigint'
    'category': 'varchar',
    'datetime64[ns, UTC]': 'timestamp'
}
```

**Comment by MichaelTiemannOSC** [comment]
Checked in expanded table above as it works.  (It's actually overkill for this specific case, but the larger range of datatypes supported make it a better source for copying to other ingestion pipelines that might have a wider range of source data types.)
