### ISSUE TITLE
Learn about PUDL metadata strategy

### ISSUE THREAD

**Issue by toki8** [os-climate/os_c_data_commons#75]
As a data designer I would like to liase with PUDL (Zane Selvans) in a call to find out how PUDL used metadata to make the data browsable and aid in modelling the datasets.

**Comment by toki8** [comment]
Have opened this, as I could not assign issues here:
https://github.com/os-c/DataCommons/issues/37

**Comment by caldeirav** [comment]
Close this as duplicate of os-c/DataCommons#37
