### ISSUE TITLE
OSC-Platform-030: Deploy (LinkedIn) Data Hub as a metadata management service

### ISSUE THREAD

**Issue by erikerlandson** [os-climate/os_c_data_commons#80]
This is a tracking issue for exploring LinkedIn's "Data Hub" project as a meta data management service for OSC.

Reference about metadata architectures and "Data Hub": https://engineering.linkedin.com/blog/2020/datahub-popular-metadata-architectures-explained.

cc @MichaelTiemannOSC @caldeirav

**Comment by caldeirav** [comment]
Deployment on kubernetes can be done with Helm charts and instructions provided at:
https://github.com/linkedin/datahub/blob/master/docs/deploy/kubernetes.md
https://github.com/acryldata/datahub-helm

Note: all dependencies should be installed first including neo4j, and preference for PostgreSQL as relational database. We may want to consider having kafka, elasticsearch, PostgreSQL and neo4j as shared services than can be used beyond DataHub (in particular the Kafka instance is required for event-driven ingestion as well). 

@redmikhail @HumairAK

**Comment by caldeirav** [comment]
@HumairAK how feasible would it be to have the helm chart-based deployment on odh-cl2 done in coming days please? Metadata ingestion is ideally the last step we want to demo in the RH Summit presentation. @erikerlandson

**Comment by caldeirav** [comment]
@HumairAK Our initial plan was to have this available in Q1 so we are a bit behind. But if you can deploy this in first half of next week, this should be enough for me to showcase some of the metadata capabilities in the RH Summit demo and from there train our internal users starting end of April, so this would be great!

**Comment by HumairAK** [comment]
I've gotten as far as installing the pre-requisite services, there are lot more tools involved here than I expected (kafka/es/mysql/neo4j etc.) and the way these are configured is new to me (requiring jobs to run to configure these with datahub). So this is taking longer than expected. I'm off Friday/Monday so I'll have to continue with this on Tuesday.

**Comment by caldeirav** [comment]
@HumairAK @redmikhail We need your help please to assess how feasible this deployment is, and if additional resources / help is required. Have also proposed an alternative at #163 which may be easier to setup.

**Comment by caldeirav** [comment]
Moving this back out of our queue as OpenMetadata has been installed, so it may not be required anymore.

**Comment by caldeirav** [comment]
Closing this issue as OpenMetadata component has now been validated to meet our needs so far.
