### ISSUE TITLE
Unable to see any schemas after 1.3.0 update

### ISSUE THREAD

**Issue by MichaelTiemannOSC** [os-climate/os_c_data_commons#92]
I'm now unable to see any schemas in the osc_datacommons_dev catalog.

**Comment by MichaelTiemannOSC** [comment]
1. Log into SuperSet 1.3.0 with github oath
2. Navigate to Data->Datasets tab
3. Click +Dataset
4. Select OSC_DataCommons_Dev catalog
5. (three dots while Superset quickly thinks)
6. Attempt to select a Schema, but there are zero schemas available.

In the bottom right corner of the window SuperSet briefly pops up that there was an error attempting to fetch schemas.

**Comment by HumairAK** [comment]
can you try again?
