### ISSUE TITLE
deploy an `odh-trino-dev` trino db

### ISSUE THREAD

**Issue by erikerlandson** [os-climate/os_c_data_commons#99]
I need a vehicle for experimenting with various trino management mechanisms, where I can play with tooling that may break a trino deployment while I develop it.  For one example, testing https://github.com/os-climate/trino-github-group-provider

**Comment by caldeirav** [comment]
Moving this to High Priority as we have upcoming design discussions on the Data Vault with LSEG and need to validate our proposed approach soon.

**Comment by HumairAK** [comment]
what bucket should I use for the starting catalogsource for this dev deployment?

**Comment by HumairAK** [comment]
Okay trino dev instance is live, created a new bucket for this called `ocp-odh-data-dev-bucket1-s3`. 

Info: 
Trino dev namespace: https://console-openshift-console.apps.odh-cl1.apps.os-climate.org/k8s/ns/odh-trino-dev/pods
Admin user creds: https://console-openshift-console.apps.odh-cl1.apps.os-climate.org/k8s/ns/odh-trino-dev/secrets/trino-admin-acct

Rules.json and other config files stored in git here: https://github.com/operate-first/apps/tree/master/kfdefs/overlays/osc/osc-cl1/trino-dev/configs

I've added it in Cloudbeaver as well.

**Comment by HeatherAck** [comment]
Awesome work!  Thank you!


Heather Ackenhusen
Principal Technical Program Manager
+1 847-687-6023 (mobile/text msg/whatsapp)
OS-Climate (Linux Foundation Contractor)



________________________________
